/**
 * session-tag-lexicon.ts — curated word pools for mnemonic session tags.
 *
 * A session tag is an `adjective-noun` pair drawn from these two disjoint pools
 * (e.g. `azure-heron`). Every word is 4–5 letters, lowercase `a-z`, and the two
 * pools never share a word, so a tag never doubles a word (`amber-amber`).
 *
 *  - {@link TAG_ADJECTIVES} — 512 words, the first half of a tag.
 *  - {@link TAG_NOUNS} — 1024 words, the second half of a tag.
 *
 * With 512 × 1024 = 524,288 combinations, the on-machine registry
 * (re-roll then numeric suffix) keeps collisions rare well past a thousand
 * sessions. Pure data — no imports, no logic.
 *
 * @module lib/session-tag-lexicon
 */

/** Adjective pool — the first word of a session tag. */
export const TAG_ADJECTIVES: readonly string[] = [
  "able", "active", "adept", "adored", "adroit", "adult", "aerial", "aged", "agile", "airy",
  "alert", "amber", "ample", "angled", "antic", "aqua", "arched", "arctic", "ardent", "argent",
  "artful", "ashen", "astral", "astute", "auburn", "august", "autumn", "avid", "aware", "azure",
  "balmy", "bare", "beefy", "beige", "bendy", "benign", "bent", "blithe", "blond", "blonde",
  "bluish", "blunt", "bold", "bonnie", "boreal", "bouncy", "boxy", "brainy", "brassy", "brave",
  "brawny", "breezy", "bright", "brisk", "broad", "bronze", "bubbly", "bumpy", "burly", "bushy",
  "canary", "candid", "canny", "caring", "chalky", "chaste", "chatty", "cheery", "cherry", "chewy",
  "chic", "chichi", "chirpy", "choice", "chosen", "chubby", "chummy", "chunky", "citric", "classy",
  "clean", "clever", "cloudy", "coarse", "cobalt", "comely", "comfy", "cool", "copper", "coral",
  "core", "cosmic", "cozy", "crafty", "creamy", "crisp", "cubic", "cuddly", "curly", "curved",
  "curvy", "cute", "cyan", "daily", "dainty", "dapper", "daring", "dear", "decent", "deft",
  "deluxe", "demure", "devout", "dewy", "dinky", "direct", "divine", "docile", "dogged", "domed",
  "doting", "doughy", "downy", "dreamy", "dressy", "drowsy", "dulcet", "dusky", "dusty", "eager",
  "early", "earthy", "easy", "edgy", "elated", "epic", "equal", "expert", "fabled", "facile",
  "faint", "fair", "famous", "fancy", "feisty", "ferny", "fervid", "fiery", "filmy", "fine",
  "firm", "first", "fizzy", "flaky", "flashy", "flat", "flaxen", "fleecy", "floaty", "floral",
  "fluent", "fluffy", "fluid", "foamy", "foggy", "fond", "formal", "frank", "free", "fresh",
  "frigid", "frilly", "frisky", "frolic", "frosty", "frothy", "fruity", "funny", "furry", "future",
  "fuzzy", "gala", "gauzy", "genial", "genius", "gentle", "gifted", "gilded", "glad", "glassy",
  "glitzy", "glossy", "golden", "goodly", "gooey", "goofy", "grand", "grassy", "gusty", "gutsy",
  "hale", "handy", "happy", "hardy", "hasty", "hazy", "hearty", "henna", "heroic", "high",
  "hilly", "holy", "homey", "honest", "huge", "humble", "humid", "hushed", "indigo", "inky",
  "intact", "ivory", "jade", "jaunty", "jolly", "jovial", "joyful", "joyous", "juicy", "junior",
  "just", "keen", "khaki", "kind", "kindly", "kingly", "knotty", "kooky", "large", "late",
  "lauded", "lavish", "leafy", "lean", "lilac", "limber", "limpid", "liquid", "lissom", "lithe",
  "little", "lively", "lofty", "loose", "lordly", "lovely", "loving", "loyal", "lucent", "lucid",
  "lumpy", "lunar", "lush", "luxe", "main", "marine", "maroon", "matte", "mature", "mauve",
  "meaty", "meek", "mellow", "merry", "mighty", "mild", "milky", "mini", "minted", "minty",
  "misty", "modern", "modest", "modish", "moral", "mossy", "muddy", "muggy", "muted", "narrow",
  "natty", "navy", "neat", "nimble", "noble", "novel", "nutty", "ochre", "olden", "olive",
  "onyx", "open", "orange", "ornate", "oval", "pale", "pastel", "peachy", "pearl", "pearly",
  "peppy", "perky", "petit", "petite", "piney", "placid", "plenty", "pliant", "plucky", "plummy",
  "plush", "plushy", "pointy", "poised", "polar", "polite", "portly", "posh", "potent", "pretty",
  "primal", "prime", "primo", "prized", "prompt", "proper", "proud", "pure", "purple", "quick",
  "quiet", "quirky", "rainy", "rare", "ready", "recent", "reedy", "regal", "retro", "rich",
  "ripe", "ritzy", "robust", "rocky", "rosy", "rotund", "rough", "round", "royal", "ruby",
  "rugged", "russet", "rustic", "sacred", "salmon", "salty", "sandy", "sassy", "satin", "satiny",
  "savory", "scarce", "secure", "seemly", "select", "sepia", "serene", "sharp", "sheer", "shiny",
  "short", "showy", "shrewd", "silent", "silken", "silky", "silly", "silver", "simple", "sinewy",
  "slant", "slate", "sleek", "sleepy", "slight", "slim", "slinky", "small", "smart", "smooth",
  "snappy", "snazzy", "snowy", "snug", "soaked", "sober", "soft", "solar", "solid", "sooty",
  "sour", "spare", "sparky", "speedy", "spiced", "spicy", "spiffy", "spiky", "spongy", "sporty",
  "spring", "spruce", "spry", "spunky", "square", "stable", "stark", "starry", "steady", "steep",
  "still", "stocky", "stony", "stormy", "stout", "strong", "sturdy", "suave", "subtle", "sudden",
  "suede", "sugary", "suited", "summer", "sunlit", "sunny", "superb", "supple", "sure", "surfy",
  "svelte", "swank", "swanky", "sylvan", "syrupy", "tall", "tame", "tangy", "tasty", "tawny",
  "teal", "teensy", "teeny", "tender", "tepid", "tidal", "tidy", "tiny", "toasty", "toned",
  "tough", "trendy", "trim", "tropic", "true", "trusty", "twilit", "umber", "unique", "upbeat",
  "urbane", "useful", "valued", "vast", "velvet", "vernal", "viney", "violet", "vital", "vivid",
  "wacky", "warm", "watery", "wavy", "waxen", "whole", "wide", "willow", "windy", "wintry",
  "wise", "witty", "woody", "woolly", "worthy", "yellow", "young", "yummy", "zany", "zenith",
  "zesty", "zippy",
];

/** Noun pool — the second word of a session tag. */
export const TAG_NOUNS: readonly string[] = [
  "abbey", "acorn", "acre", "actor", "adder", "agate", "aioli", "alarm", "alder", "alley",
  "alloy", "aloe", "altar", "angel", "anise", "anvil", "apex", "aphid", "apple", "apron",
  "arbor", "arch", "arena", "aspen", "aster", "atlas", "atoll", "attic", "auger", "aura",
  "axle", "baby", "bacon", "badge", "bagel", "baker", "ball", "balm", "balsa", "band",
  "banjo", "bank", "barb", "bard", "barge", "bark", "barn", "basil", "basin", "bass",
  "baton", "bayou", "beach", "bead", "beam", "bean", "bear", "beech", "beet", "bell",
  "belt", "bench", "beret", "berm", "berry", "beryl", "betta", "bike", "birch", "bird",
  "bison", "blaze", "blimp", "bliss", "block", "bloom", "bluff", "boar", "board", "boat",
  "bolt", "book", "boon", "boot", "booth", "bower", "bowl", "brace", "braid", "brake",
  "bran", "brass", "bread", "bream", "briar", "brick", "brine", "brink", "brook", "broom",
  "broth", "brush", "buck", "bugle", "bulb", "bull", "bunny", "buoy", "burl", "burn",
  "bush", "butte", "cabin", "cable", "cacao", "cadet", "cafe", "cake", "calf", "calla",
  "calm", "camel", "cameo", "canal", "candy", "canoe", "cape", "caper", "carol", "carp",
  "cart", "cave", "cedar", "cello", "chai", "chain", "chair", "chalk", "chard", "charm",
  "chart", "cheer", "chef", "chess", "chest", "chia", "chick", "chief", "child", "chili",
  "chill", "chime", "chip", "chive", "choir", "chord", "chuck", "churn", "chute", "cider",
  "city", "clam", "clamp", "clasp", "clay", "clear", "clerk", "cliff", "clip", "cloak",
  "clock", "cloth", "cloud", "clove", "coach", "coal", "coast", "coat", "cobra", "cocoa",
  "coin", "cola", "cold", "colt", "comb", "comet", "conch", "condo", "cone", "coop",
  "coot", "copse", "cord", "cork", "corn", "couch", "coupe", "court", "cove", "crab",
  "craft", "crag", "crane", "crank", "crate", "cream", "creed", "creek", "crepe", "cress",
  "crest", "croc", "crock", "croft", "crow", "crowd", "crown", "crumb", "crust", "cuff",
  "cumin", "cuppa", "curd", "curry", "cycle", "dairy", "daisy", "dale", "date", "dawn",
  "deck", "deed", "deer", "dell", "delta", "denim", "depot", "desk", "dhow", "dial",
  "dike", "dill", "diner", "dingo", "disc", "dish", "disk", "diver", "dock", "doll",
  "dome", "donor", "donut", "door", "dough", "dove", "draft", "drake", "drama", "dream",
  "dress", "drift", "drill", "drum", "dryad", "duck", "dune", "dusk", "dust", "dwarf",
  "eagle", "earth", "easel", "eaves", "ebony", "eddy", "egret", "elder", "ember", "envoy",
  "ether", "even", "event", "fable", "face", "fairy", "faith", "falls", "farm", "faun",
  "fava", "favor", "fawn", "feast", "feat", "fell", "felt", "fence", "fern", "ferry",
  "feta", "fiber", "field", "fife", "file", "filly", "finch", "fire", "firth", "fish",
  "fjord", "flag", "flame", "flan", "flare", "flash", "flask", "flax", "flea", "fleet",
  "floor", "flora", "floss", "flour", "flow", "fluke", "flume", "flute", "foal", "foam",
  "font", "ford", "forge", "fork", "fort", "fount", "foyer", "frame", "frock", "frog",
  "frond", "front", "frost", "froth", "fruit", "fudge", "gable", "gale", "game", "gamer",
  "gate", "gator", "gauge", "gauze", "gear", "gecko", "genie", "geode", "ghee", "gift",
  "glade", "glare", "glass", "glaze", "gleam", "glen", "glint", "globe", "glory", "glove",
  "glow", "gnat", "gnome", "goat", "gold", "golem", "gong", "goose", "gorge", "gorse",
  "gourd", "gown", "grace", "grain", "grape", "graph", "grass", "gravy", "grit", "grits",
  "group", "grove", "guava", "guest", "guide", "gulch", "gulf", "gull", "gully", "gumbo",
  "guppy", "guru", "gust", "gyro", "habit", "hail", "hair", "hake", "hall", "halo",
  "hand", "hare", "harp", "haven", "hawk", "haze", "heart", "heat", "heath", "helm",
  "hemp", "herb", "hero", "heron", "hill", "hind", "hinge", "hive", "hoar", "hobby",
  "holly", "home", "honey", "honor", "hood", "hook", "hope", "horn", "horse", "hotel",
  "hound", "hour", "house", "hull", "hump", "humus", "hymn", "ibex", "ibis", "idea",
  "inlet", "iris", "iron", "isle", "islet", "jeep", "jelly", "jerky", "jetty", "jewel",
  "joey", "judge", "juice", "jute", "kale", "kayak", "kazoo", "kebab", "keel", "keep",
  "kilt", "kiosk", "kite", "kitty", "kiwi", "knob", "knoll", "knot", "koala", "krill",
  "label", "lace", "ladle", "lager", "lake", "lamb", "lamp", "land", "lane", "larch",
  "lark", "larva", "lasso", "latch", "lathe", "latte", "lawn", "lead", "leaf", "ledge",
  "leek", "lemon", "lemur", "lens", "levee", "level", "lever", "light", "lily", "lime",
  "linen", "liner", "ling", "lion", "llama", "loaf", "loam", "lobby", "loch", "lock",
  "lodge", "logic", "loon", "lore", "lotus", "ludo", "lunch", "lynx", "lyre", "macaw",
  "mace", "mahi", "maize", "mako", "mall", "mamba", "mango", "manor", "manta", "maple",
  "mare", "marsh", "mash", "mason", "mast", "match", "mayor", "mead", "meal", "meat",
  "medal", "melon", "mercy", "mere", "merit", "mesa", "meter", "mica", "midge", "milk",
  "mill", "miner", "mink", "mint", "miso", "mist", "mite", "moat", "mocha", "mochi",
  "mole", "molly", "monk", "month", "moon", "moor", "moose", "morn", "moss", "motel",
  "moth", "motor", "mound", "mount", "mouse", "mouth", "movie", "mule", "mural", "muse",
  "myth", "naan", "nacho", "naiad", "nail", "nave", "nest", "newt", "niche", "niece",
  "night", "noon", "notch", "nova", "nurse", "nymph", "oasis", "oath", "oboe", "ocean",
  "okra", "omen", "onion", "opal", "opera", "orbit", "orca", "order", "organ", "oryx",
  "oscar", "otter", "oven", "page", "pail", "paint", "palm", "panda", "panel", "pansy",
  "paper", "park", "pass", "pasta", "path", "patio", "patty", "pawn", "peace", "peach",
  "peak", "pear", "peat", "pecan", "pedal", "penne", "penny", "peony", "perch", "pesto",
  "petal", "phlox", "phone", "photo", "piano", "piece", "pier", "pika", "pike", "pilaf",
  "pilot", "pine", "pinto", "pipe", "pita", "pixie", "pizza", "plaid", "plain", "plane",
  "plank", "plate", "plaza", "plum", "poet", "point", "polo", "polyp", "pond", "pony",
  "pool", "poppy", "porch", "post", "pouch", "prawn", "prism", "prize", "prong", "prow",
  "prune", "puma", "pump", "pupa", "pupil", "puppy", "puree", "purse", "pylon", "quail",
  "quay", "quest", "quill", "quilt", "racer", "radio", "raft", "rail", "rain", "rake",
  "ramen", "ramp", "ranch", "rapid", "rasp", "raven", "razor", "realm", "reed", "reef",
  "reel", "relay", "relic", "rhino", "rhyme", "rice", "rider", "ridge", "rill", "rime",
  "ring", "rise", "river", "rivet", "roach", "road", "roast", "robe", "robin", "rock",
  "roll", "roof", "rook", "room", "root", "rope", "rose", "rover", "rowan", "ruff",
  "rugby", "ruler", "rune", "sack", "saga", "sage", "sail", "salad", "salsa", "salt",
  "sand", "sash", "satyr", "sauce", "scale", "scarf", "scarp", "scene", "scone", "scope",
  "score", "scout", "scree", "screw", "scrub", "seal", "sedan", "sedge", "seed", "shade",
  "shaft", "shake", "shale", "shark", "shawl", "shed", "sheep", "sheet", "shelf", "shell",
  "shim", "shine", "ship", "shirt", "shoal", "shoe", "shoot", "shop", "shore", "shrew",
  "shrub", "sieve", "silk", "silo", "silt", "siren", "sisal", "sitar", "skate", "skiff",
  "skink", "skirt", "sled", "sleet", "sloop", "slope", "sloth", "smelt", "smile", "smith",
  "smock", "smoke", "snack", "snail", "snake", "snipe", "snow", "soap", "sock", "soda",
  "sofa", "soil", "sole", "solo", "song", "sora", "sound", "soup", "space", "spade",
  "spar", "spark", "spell", "spelt", "spice", "spine", "spire", "spit", "spoke", "spool",
  "spoon", "spore", "spout", "spray", "sprig", "spur", "squid", "stack", "staff", "stag",
  "stage", "stair", "stalk", "stall", "stamp", "star", "steam", "steed", "steel", "steer",
  "stem", "stew", "stilt", "stoat", "stock", "stone", "stool", "store", "stork", "storm",
  "story", "stove", "straw", "stud", "sugar", "suit", "suite", "surf", "surge", "sushi",
  "swamp", "swan", "sweet", "swell", "swift", "sylph", "syrup", "table", "tabor", "taco",
  "taffy", "talc", "tale", "tang", "tango", "tapas", "taper", "tapir", "tarn", "tart",
  "teak", "tempo", "tent", "tern", "tetra", "thaw", "thyme", "tide", "tiger", "tile",
  "timer", "tire", "titan", "toad", "toast", "tofu", "token", "tongs", "tonic", "tool",
  "topaz", "torch", "torte", "towel", "tower", "town", "track", "trail", "train", "tray",
  "treat", "tree", "trout", "truck", "truth", "tube", "tulip", "tuna", "tune", "tunic",
  "turf", "tutor", "tweed", "twig", "twine", "udon", "umbra", "uncle", "unity", "usher",
  "vale", "valor", "valve", "vapor", "vase", "vault", "veil", "verse", "vest", "villa",
  "vine", "viol", "viola", "viper", "vise", "visor", "vista", "vixen", "vole", "wafer",
  "wagon", "wake", "wall", "waltz", "wand", "wash", "wasp", "watch", "water", "wave",
  "weave", "wedge", "week", "weir", "well", "whale", "wharf", "wheat", "wheel", "whelk",
  "whey", "whiff", "whirl", "whisk", "wick", "winch", "wind", "wing", "wire", "wish",
  "wolf", "wood", "wool", "world", "wrap", "wren", "yacht", "yard", "yarn", "yeast",
  "yeti", "yucca", "zebra", "zinc",
];

/** Total distinct `adjective-noun` combinations. */
export const TAG_COMBINATIONS = TAG_ADJECTIVES.length * TAG_NOUNS.length;
