/**
 * TugProgressPulsingDot — Internal building block for the breathing-dot glyph.
 *
 * App code should use {@link TugProgressIndicator} instead.
 *
 * The glyph **breathes** — the inner dot scales up and down on a continuous
 * 2s cycle, and the ring is emitted from that breath rather than clocked on
 * its own. It supersedes an earlier dot of the same name that held a fixed
 * circle and chained one-shot WAAPI ring pulses around it; that one was a
 * blinker with a halo, and this one is a thing that inhales and exhales.
 *
 * Two visible elements on ONE shared 2s period:
 *
 *   - **Dot** — a solid circle that rises to full size and sinks back
 *     over the cycle, traveling the full swing every time. Its color
 *     resolves from the parent's live `--tugx-progress-indicator-fill`.
 *   - **Ring** — fired a few degrees before the top of the breath, so it
 *     is already alive and moving when the dot turns. It is born at the
 *     dot's own edge and expands outward to the glyph box, fading as it
 *     goes — so the exhale is one gesture: the dot falls away from the
 *     ring it just shed. Below 28px it is let out past the box; see
 *     {@link sizeGeometry}.
 *
 * **The envelope is not symmetric.** The dot rises over the first 30% of
 * the cycle and sinks over the remaining 70% — quick in, slow out, the
 * shape of the colon blink on an Apple Watch digital time label. A breath
 * that takes as long going up as coming down reads as a mechanism; this
 * one reads as something alive. The whole curve, both legs and the ring's
 * ignition, lives in the sampled stops of the stylesheet's `@keyframes`
 * blocks, generated by {@link breathKeyframes} — never in a multi-stop
 * `linear()` easing, which WebKit cannot hand to the compositor. The
 * gallery's timing bench injects alternative keyframe blocks and points
 * the `--…-*-name` variables at them to show cuts side by side.
 *
 * **Phase lock without a clock.** Both elements run CSS `@keyframes` on
 * the same duration, started in the same frame, so the ring's emission
 * stays welded to the dot's turn with no timer, no WAAPI chaining, and no
 * per-frame main-thread work. Every dot in the app runs that same duration
 * unless its caller opts into a jitter ({@link dotDriftFor}), which only the
 * Lens's session list does. Firing near the turn also keeps the ring inside a
 * single cycle, so the pulse needs no wrap across the cycle boundary.
 *
 * Same frame is the whole of it, and the loops live on two elements behind two
 * separate gates, so it is a thing to be ENFORCED rather than assumed. The lock
 * has exactly one enemy: starting one loop while the other is already running.
 * There is no clock to re-sync against and no cycle boundary to recover on — a
 * glyph that starts its two loops a quarter cycle apart sheds rings out of the
 * breath for as long as it runs, and writing a gate that is already set starts
 * nothing, so the mistake is not even visible at the call. Every start
 * therefore goes through {@link startLoops}, which closes both gates and
 * flushes the removal before opening either.
 *
 * The one arrival that cannot start both at once is work RESUMING while the
 * last settle's pulse is still travelling — the ordinary way work resumes,
 * since a pulse is in the air for most of a cycle. The ring is spoken for and
 * the breath will not wait for it, so the two are started apart on purpose:
 * the breath goes at once at the dot's own phase, the pulse finishes its
 * travel, and the emitter then REJOINS the breath's clock at a phase where the
 * ring paints nothing ({@link rejoinEmitter}). They carry separate phase
 * variables for exactly this window, so starting one never disturbs the other.
 *
 * **Two treatments.** The glyph serves both a 28px Lens row and a 10px status
 * cell, and it does that by carrying two geometries rather than scaling one —
 * see {@link BIG_SIZE}. The motion below is common to both; the proportions,
 * the ring's reach, and the PRESENCE ladder are not.
 *
 * **No state change is a cut.** The glyph's state changes when the work does,
 * on a frame nobody chose, with the dot somewhere in the middle of a breath and
 * possibly a ring in mid-flight. Letting CSS gate the loops on `data-state`
 * made that arrival a tear: the ring vanished wherever it happened to be and
 * the dot jumped to its resting pose. So the motion is gated on two attributes
 * this component writes — `data-breathing` and `data-emitting` — and every
 * arrival is a CROSSING instead:
 *
 *   - A lit pulse **always finishes its travel**. It was shed; it is leaving
 *     under its own momentum, and the work ending is no business of its. The
 *     emitter is released on the pulse's clock, not the state's ({@link
 *     releaseEmitter}). A pulse that was never lit is simply not lit.
 *   - The dot **is caught where it stands**: its live scale is pinned inline,
 *     the loop is dropped against that pin, and a CSS transition carries it
 *     from there to the settled pose. Entering `running` is the same idea
 *     inverted — the loop starts at the phase whose pose the dot already holds
 *     ({@link breathPhaseFor}), so the breath picks it up mid-stride.
 *   - The static ring **fades**, and the tint **crosses**, on that same
 *     duration, so the whole arrival reads as one gesture.
 *
 * State semantics, each rung also carrying its own PRESENCE — its share of the
 * reserved box ({@link SETTLED_PRESENCE}), so at the big end the glyph's SIZE
 * reads the state before its color or motion does:
 *   running   — the dot breathes and emits rings; owns the whole box.
 *   paused    — dot held at full size; static outer ring, drawn in.
 *   stopped   — quiet (reduced) dot; small static ring.
 *   completed — quiet dot; small static ring, success tint from parent.
 *   aborted   — full-size dot; static outer ring drawn in, danger tint.
 *
 * **Settled states render settled DOM — the end-state swap.** Progress
 * machinery is for progress. A dot that has reached an end state and is not
 * mid-crossing renders in **static mode**: same spans, same box, same visible
 * circles, but the dot is sized by width/height instead of a transform,
 * centered by `inset`/`margin` instead of a translate, and carries **no
 * `transition` and no animation attributes** — so it holds no stacking
 * context, no compositing layer, and no retained `CSSTransition`. That is not
 * a nicety: a restored transcript mounts one of these per historical tool
 * call, and a few hundred settled-but-live dots were measured at 82% of a
 * heavy card's composited breadth, walked twice per keystroke. A dot born
 * settled is static from its first render and no motion machinery ever runs.
 *
 * The **live↔static handoff never cuts** ({@link armDemotion}):
 *   - static→live promotion happens synchronously in the crossing layout
 *     effect, before the crossing plays — the live DOM's first frame is
 *     seeded to the exact pose the static DOM was painting;
 *   - live→static demotion follows the RULE: **swap when settled.** The
 *     glyph demotes only once everything under it has come to rest — the
 *     settle transition done (`transitionend`, with a resolved-duration
 *     fallback), no pulse in flight (`data-emitting` released on the pulse's
 *     own clock), nothing else animating under the root, and one frame of
 *     grace — so the swap replaces DOM that has painted its final pose with
 *     DOM that paints the identical pose. A new state during the window
 *     abandons the demotion; the machine stays live for the new crossing.
 *     Late is free, early is a glitch: static mode is a cost optimization
 *     with no deadline.
 *
 * Laws: [L02] state arrives via props from the parent indicator;
 *       [L06] tone is a live CSS variable, and the crossing between states is
 *       CSS transitions driven by DOM attributes and one inline pose — the
 *       state currently on screen is a ref, never React state, so a crossing
 *       renders nothing. The render MODE (static | live) is React state
 *       deliberately: it is a STRUCTURE change (different DOM contract), which
 *       is exactly what renders are for; appearance within a mode still never
 *       renders;
 *       [L13] the breath and the ring are continuous loops, so they are
 *       declarative CSS `@keyframes` (motion-off zeroes them through the
 *       global `body[data-tug-motion="off"]` rule, which zeroes the settle's
 *       transitions with them — the demotion's duration fallback reads the
 *       RESOLVED duration, so motion-off collapses the settle window to ~0
 *       rather than stalling it). The script here starts and releases those
 *       loops and hands off between them; it never drives a frame.
 *
 * @module components/tugways/internal/tug-progress-pulsing-dot
 */

import "./tug-progress-pulsing-dot.css";

import React from "react";

import { cn } from "@/lib/utils";
import type { TugProgressIndicatorState } from "../tug-progress-indicator";

/**
 * Glyph box diameter when the caller names no size. Sized against the Z5
 * submit button (36px square) — this glyph is meant to be legible across
 * the room the way that button is. It runs a little under, since motion
 * carries some of the load that size alone carries for a static control.
 */
const DEFAULT_SIZE = 32;

/**
 * Dot diameter as a fraction of the glyph box, at the top of the breath.
 *
 * At the big end the dot IS the object being looked at, so it takes most of the
 * box and the remainder is the room the emitted ring expands into. At the small
 * end it is {@link SMALL_DOT_RATIO} instead — the previous glyph's ratio, kept
 * so a settled marker in a status row is the size it has always been.
 */
const DOT_RATIO = 0.6;

/** The small treatment's dot ratio — the previous glyph's, unchanged. */
const SMALL_DOT_RATIO = 0.5;

/**
 * Trough of the breath — the dot's scale at the bottom of the cycle. A
 * wide swing on purpose: the dot travels the full distance every cycle,
 * and the ring's emission is a waypoint on the way down, not the end of
 * the fall. Mirrors `--tugx-progress-pulsing-dot-dot-scale-min`.
 */
const DOT_SCALE_MIN = 0.35;

/**
 * How far before the turn the ring is lit, as a fraction of the cycle —
 * **ignition advance**, borrowed from a spark engine. The turn is top dead
 * center; the spark fires a few degrees before it, so the pressure is already
 * building when the piston turns. Read the cycle as 360°, 3% is **10.8°
 * BTDC** — a plausible advance for a real engine, and the same reasoning
 * applies here. The ring needs a few frames to become visible and start
 * moving; lighting it exactly at the turn means the eye catches it slightly
 * late, trailing the dot.
 */
const EMIT_ADVANCE = 0.03;

/** Turn of the shipped envelope — the CSS defaults are `breathEnvelope(0.3)`. */
export const DEFAULT_BREATH_TURN = 0.3;

/**
 * The size band across which this glyph changes what it is trying to be.
 *
 * There are two treatments here, not one figure scaled. At {@link BIG_SIZE} and
 * up — the Lens session row — it is a figure meant to be read across a room:
 * the dot takes 60% of the box, the ring stays inside it, and the PRESENCE
 * ladder encodes state as relative size. At {@link SMALL_SIZE} and down — a Z2
 * status cell, a tool-call header, a setup step — it is a marker in a row of
 * type, and every one of those choices is wrong for it: relative size is not
 * legible in 12 pixels, and a bigger dot is just a bigger dot.
 *
 * **The small treatment is the previous glyph's geometry, exactly.** Same 0.5
 * dot ratio, same full-box static ring, same hairline stroke, no ladder — so a
 * settled dot in a status cell paints the pixels it painted before. What
 * changes down there is the MOTION and nothing else: the dot breathes and sheds
 * a ring instead of holding still under a halo. That is the whole point of
 * unifying the variants, and it is the whole extent of it.
 *
 * The band is chosen to sit in the gap between the real call sites: everything
 * the app asks for is 16px and under or 28px and over, so nothing ships at a
 * blend. The ramp between exists so the in-between sizes a gallery or a future
 * caller might pick degrade smoothly rather than snapping at a threshold.
 */
const BIG_SIZE = 28;
const SMALL_SIZE = 16;

/** 0 at {@link BIG_SIZE} and up, 1 at {@link SMALL_SIZE} and down. */
function smallness(size: number): number {
  return Math.min(1, Math.max(0, (BIG_SIZE - size) / (BIG_SIZE - SMALL_SIZE)));
}

/**
 * How far past the glyph box a small ring travels.
 *
 * Layout-safety is a luxury of size. Held inside the box, the ring's whole
 * journey is from the dot's edge to the box edge — at a 32px glyph that is
 * 6.5px of radius and reads as a pulse; at 12px it is 2.5px and reads as a
 * twitch, a ring that appears, shivers, and stops. There is no timing fix for
 * that: the distance simply is not there.
 *
 * So below {@link BIG_SIZE} the ring is let out of the box, ramping to
 * this multiple at {@link SMALL_SIZE} and under. It is not a new idea —
 * it is what the glyph this one replaces always did (its ring ran to 1.9× the
 * box), and it is why that glyph read at 12px at all. Overflow is free here:
 * the ring is absolutely positioned and nothing on the path clips, so a bigger
 * reach costs paint, never layout.
 */
const REACH_MAX = 1.75;

/**
 * The small treatment's trough — a much shallower breath than the big one's.
 *
 * Depth of breath does not survive being scaled down, because the bottom of the
 * swing is where the dot is least able to spare anything. {@link DOT_SCALE_MIN}
 * takes a 19.2px dot down to 6.7px, which still reads as a dot; the same ratio
 * takes a 6px dot down to 2.1px, which reads as a dot going out. And unlike the
 * big glyph, the small one is sitting in a row of type where it is the only
 * mark: it cannot afford to half-disappear on every cycle.
 *
 * So the swing narrows as the glyph shrinks, to this at {@link SMALL_SIZE} and
 * under — a modulation rather than a full breath. The motion is still legible
 * down there because the shed ring is carrying most of it; the dot's job at
 * these sizes is to stay a dot.
 */
const SMALL_TROUGH = 0.7;

/**
 * Everything about the glyph that cannot be one number across a 10px–40px
 * range, derived from the size in one place.
 *
 * The timing is untouched by any of it — the envelope, the ignition advance and
 * the stroke weights are scale-free and every size gets the same breath. What
 * changes is geometry, because each of these is a ratio against a box that is
 * no longer one size:
 *
 *   - **ratio** — the dot's share of the box. 0.6 big, 0.5 small (the previous
 *     glyph's), so a settled small dot is the size it always was.
 *   - **reach** — where the ring's expansion ends. The box edge at the big end,
 *     and out past it at the small end, where the box is not far enough away to
 *     be worth traveling to.
 *   - **scaleMin** — the trough of the breath. A deep swing at the big end, a
 *     shallow modulation at the small one, where the dot cannot spare the
 *     pixels and the ring is carrying the motion anyway.
 *   - **birth** — where the dot's edge is when the spark fires. Falls out of
 *     the other two; it is here so it cannot drift from them.
 *
 * All four are published as `-auto` variables so an override from above still
 * wins (see the stylesheet's note on the knobs), and all four resolve to the
 * stylesheet's own defaults at {@link BIG_SIZE} and up.
 */
export function sizeGeometry(size: number): {
  ratio: number;
  reach: number;
  scaleMin: number;
  birth: number;
} {
  const t = smallness(size);
  const ratio = DOT_RATIO + (SMALL_DOT_RATIO - DOT_RATIO) * t;
  const scaleMin = DOT_SCALE_MIN + (SMALL_TROUGH - DOT_SCALE_MIN) * t;
  const atIgnition = breathAt(
    DEFAULT_BREATH_TURN,
    DEFAULT_BREATH_TURN - EMIT_ADVANCE,
  );
  return {
    ratio,
    reach: 1 + (REACH_MAX - 1) * t,
    scaleMin,
    // Where the dot's edge actually is when the spark fires. It moves with the
    // ratio and the trough, so it is derived here rather than left to the
    // stylesheet's big-size default — otherwise a small ring is born beside the
    // dot instead of on it.
    birth: ratio * (scaleMin + (1 - scaleMin) * atIgnition),
  };
}

/**
 * Exponent of the ring's opacity falloff — 1 is an even fade, and every step
 * up front-loads it harder.
 *
 * Shipped even. The pulse's problem was never the shape of its exit, it was
 * that it was born at partial strength: a ring that starts pre-faded and then
 * dims uniformly reads as grey. Fix the birth (see `--…-emit-opacity`) and the
 * even fall is the one that reads as a ring travelling outward and thinning.
 * Front-loading on top of that mostly shortens the ring's visible life, which
 * costs more than the extra snap buys.
 */
export const DEFAULT_FADE_POWER = 1;

/**
 * Shipped pulse stroke weight, mirroring the fallback on
 * `--tugx-progress-pulsing-dot-pulse-weight`.
 *
 * It is the weight the pulse ENDS at, as a multiple of the resting ring's — not
 * the weight it carries throughout. The stroke opens across the ring's travel,
 * from a 1px hairline at ignition to this as the ring reaches the box and fades
 * out: sharp where it is brightest, soft where it is leaving. The stylesheet
 * pre-divides both ends by the scale they paint at, since a border on a
 * `transform: scale`d element renders at border × scale.
 *
 * Read it as an intent rather than a rendered ratio: borders resolve to device
 * pixels, so at the sizes this glyph runs at (a 28px Lens row, a 32px bench
 * cell) neighboring weights can paint identically.
 */
export const DEFAULT_PULSE_WEIGHT = 1.6;

/**
 * The breath's shape at progress `p`, for a cycle that turns at `turn`.
 *
 * Each leg is its own cosine ease-in-out, fitted to its own length rather than
 * one curve skewed across the turn. That is the part that matters: a cosine
 * arrives at its endpoint with zero velocity, so however quick the rise, it
 * settles into a HOLD at the top instead of hitting a corner, and the long
 * fall then drifts away from that hold. Rise, hover, sink.
 */
function breathAt(turn: number, p: number): number {
  return p <= turn
    ? (1 - Math.cos(Math.PI * (p / turn))) / 2
    : (1 + Math.cos(Math.PI * ((p - turn) / (1 - turn)))) / 2;
}

/** Trim a computed stop to something readable in a stylesheet. */
function stop(n: number): string {
  const s = n.toFixed(4).replace(/0+$/, "").replace(/\.$/, "");
  return s === "" || s === "-0" ? "0" : s;
}

/**
 * The whole envelope for a given turn, as the three `@keyframes` blocks the
 * stylesheet carries — the SHAPE, not an easing.
 *
 * The shape has to live in the stops. An earlier cut put it in `linear()`
 * easings over two-stop keyframes, which made the curve a single-variable knob
 * and cost the glyph everything: Core Animation expresses a segment's easing as
 * a cubic bezier, a multi-stop `linear()` is not one, and WebKit answers by
 * declining to accelerate the animation at all. On a 100-glyph bench that was
 * the difference between 18.0% of the main thread and 0.9%.
 *
 * Sampling the same curve into keyframe stops and interpolating linearly
 * between them is the same envelope by construction, and Core Animation runs it
 * natively. Hand this a different turn and the dot's legs, the ring's ignition
 * and the radius it is born at all move together, exactly as before — the knob
 * survived, it just changed which property it turns.
 *
 * `breathKeyframes(DEFAULT_BREATH_TURN, "tugx-progress-pulsing-dot")` is what
 * the stylesheet's blocks were generated from; regenerate them together if the
 * turn changes.
 *
 *   - **breathe** — the dot. Runs 0 → 1 → 0 across the cycle, so a two-stop
 *     keyframe (min → full) plays out and back on a single pass.
 *   - **expand** — the ring's radius. Flat at 0 until ignition (the ring
 *     parked, unlit, at the dot's edge), then a cubic ease-out to the box.
 *   - **fade** — the ring's opacity, on a keyframe that runs lit → 0. Held at
 *     1 (i.e. invisible) through the inhale, stepped to 0 in a hairline
 *     between two stops at the same position, then a power falloff back to 1
 *     ({@link DEFAULT_FADE_POWER}, shipped even). The ring is at nearly full
 *     strength for the frames it is still on the dot's edge, then thins evenly
 *     as it travels. Radius and opacity are separate animations because their
 *     HOLDS are opposite (radius parked at 0, opacity parked at 1) and because
 *     their shapes are specified independently.
 *   - **emit-birth** — the dot's own scale at ignition × {@link DOT_RATIO}, so
 *     the ring peels off the dot's edge rather than appearing beside it.
 */
export function breathKeyframes(turn: number, prefix: string): string {
  const RISE_STOPS = 8;
  const FALL_STOPS = 12;
  const EXPAND_STOPS = 12;
  const ignition = turn - EMIT_ADVANCE;
  const TROUGH = "var(--tugx-progress-pulsing-dot-trough-resolved)";
  const BIRTH = "var(--tugx-progress-pulsing-dot-birth-resolved)";
  const REACH = "var(--tugx-progress-pulsing-dot-reach-resolved)";
  const pose = (scale: string): string =>
    `    transform: translate(-50%, -50%) scale(${scale});`;

  const breathe: string[] = [];
  const at = (p: number): void => {
    const v = breathAt(turn, p);
    const scale =
      v <= 0 ? TROUGH : v >= 1 ? "1" : `calc(${TROUGH} + (1 - ${TROUGH}) * ${stop(v)})`;
    breathe.push(`  ${stop(p * 100)}% {\n${pose(scale)}\n  }`);
  };
  for (let i = 0; i <= RISE_STOPS; i++) at((turn * i) / RISE_STOPS);
  for (let i = 1; i <= FALL_STOPS; i++) at(turn + ((1 - turn) * i) / FALL_STOPS);

  const expand: string[] = [
    `  0%,\n  ${stop(ignition * 100)}% {\n${pose(BIRTH)}\n  }`,
  ];
  for (let i = 1; i <= EXPAND_STOPS; i++) {
    const u = i / EXPAND_STOPS;
    const p = ignition + u * (1 - ignition);
    const w = 1 - (1 - u) ** 3;
    const scale =
      w >= 1 ? REACH : `calc(${BIRTH} + (${REACH} - ${BIRTH}) * ${stop(w)})`;
    expand.push(`  ${stop(p * 100)}% {\n${pose(scale)}\n  }`);
  }

  const fade = [
    `  0%,\n  ${stop(ignition * 100 - 0.01)}% {\n    opacity: 0;\n  }`,
    `  ${stop(ignition * 100)}% {\n    opacity: var(--tugx-progress-pulsing-dot-emit-opacity, 0.95);\n  }`,
    `  100% {\n    opacity: 0;\n  }`,
  ];

  return [
    `@keyframes ${prefix}-breathe {\n${breathe.join("\n")}\n}`,
    `@keyframes ${prefix}-emit-expand {\n${expand.join("\n")}\n}`,
    `@keyframes ${prefix}-emit-fade {\n${fade.join("\n")}\n}`,
  ].join("\n\n");
}

/**
 * Half-width of the period jitter, as a fraction of the nominal 2s cycle.
 *
 * The point is a column of them. Several sessions breathing on one exact
 * period read as one mechanism with several heads; give each its own rate and
 * they pull apart over half a minute or so into something that reads as
 * several things each doing its own work. At ±4% the widest pair differs by
 * ~160ms per cycle, so neighbors take roughly a dozen breaths to fall out of
 * step — slow enough that no single glance catches the drift happening.
 *
 * It only ever scales the period, so every loop under one draw still reads
 * the same duration and stay phase-locked: the ring is still shed at 10.8° BTDC
 * of that breath.
 */
const DRIFT_SPREAD = 0.04;

/**
 * The jitter for one item, as the style that carries it — spread `key` over
 * `[1 - DRIFT_SPREAD, 1 + DRIFT_SPREAD]` and pin it.
 *
 * **Drift is opt-in, and almost nothing opts in.** It is not a property of the
 * glyph and not a property of the indicator either; it is a property of a LIST
 * OF ITEMS, and the only such list is the Lens's session rows. Every other
 * pulsing dot in the app runs the nominal period, locked — which is what the
 * Z2 STATE cell needs, since it renders two separate indicators flanking one
 * label and they have to read as one status. Automatic drift, at either level,
 * had that pair breathing against each other.
 *
 * So the caller names the item and gets its rate:
 *
 *     <TugProgressIndicator variant="pulsing-dot" style={dotDriftFor(cardId)} />
 *
 * Keyed rather than drawn, because identity is what the jitter is supposed to
 * track. A random draw per mount would re-roll a session's rate every time the
 * Lens filtered, scrolled it out and back, or hot-reloaded; hashing the id
 * means a session breathes at its own rate for as long as it exists, and two
 * rows never collide by accident of timing. It also needs no state, so it
 * survives every remount for free.
 */
export function dotDriftFor(key: string): React.CSSProperties {
  // FNV-1a, 32-bit. Any cheap avalanche would do — what matters is that
  // neighboring ids (`card-1`, `card-2`) land far apart rather than adjacent.
  let hash = 0x811c9dc5;
  for (let i = 0; i < key.length; i++) {
    hash ^= key.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  const unit = (hash >>> 0) / 0x100000000;
  const drift = 1 + (unit * 2 - 1) * DRIFT_SPREAD;
  return {
    ["--tugx-progress-pulsing-dot-drift" as string]: drift.toFixed(4),
  } as React.CSSProperties;
}

/**
 * Cycle position where the ring is lit — the frame a pulse begins to exist.
 * Before it, the ring is parked and fully faded and there is nothing to finish.
 */
const IGNITION = DEFAULT_BREATH_TURN - EMIT_ADVANCE;

/**
 * Slack on the emitter's release, in ms.
 *
 * A late release is free and an early one is not, so the timer is deliberately
 * generous. The ring reaches opacity 0 at the end of its travel and stays there
 * for the next 27% of the following cycle, so dropping the animation anywhere in
 * that window paints identically; cutting it a frame EARLY clips the tail of a
 * visible pulse, which is the whole thing being avoided.
 */
const EMIT_RELEASE_SLACK = 32;

/**
 * The custom properties the arming phase is written to — one per loop.
 *
 * They carry the same number whenever both loops are started together, which is
 * almost always. They are two because the loops can be started APART: a breath
 * resuming while the last settle's pulse is still travelling has to take its
 * phase without dragging the flying ring's delay along with it, which a shared
 * variable would do — and moving a running animation's delay moves the
 * animation.
 */
const PHASE_VAR = "--tugx-progress-pulsing-dot-phase";
const EMIT_PHASE_VAR = "--tugx-progress-pulsing-dot-emit-phase";

/** The dot's transform at a given breath scale. */
function dotPose(scale: number): string {
  // The same function list the keyframes write — translate, then scale.
  // Transforms interpolate componentwise only between matching lists; a pose
  // written in any other shape would decompose to a matrix at the handoff,
  // which is the frame the handoff exists to hide.
  return `translate(-50%, -50%) scale(${scale})`;
}

/**
 * The scale the dot is painting at RIGHT NOW — the animated value, not the
 * declared one.
 *
 * This is the whole mechanism behind a smooth exit. A state change arrives on
 * an arbitrary frame, with the dot at an arbitrary point in its breath, and the
 * only way out that does not jump is to start the settle from the pose actually
 * on screen. `getComputedStyle` resolves animations, so it reports that pose;
 * the caller pins it inline before dropping the loop, and the removal becomes a
 * no-op the eye cannot see.
 */
function liveScale(el: HTMLElement): number | null {
  const value = getComputedStyle(el).transform;
  if (!value || value === "none") return null;
  try {
    return new DOMMatrixReadOnly(value).a;
  } catch {
    return null;
  }
}

/**
 * Where the breath is in its cycle right now, and how long that cycle is —
 * `null` when the dot is not breathing.
 *
 * Read off the running animation rather than tracked, for the same reason
 * {@link liveScale} is: the loop is the authority on where the loop is, and
 * anything the script remembers instead would drift the moment a duration, a
 * drift factor or a motion setting changed underneath it.
 */
function breathClock(dot: HTMLElement): { phase: number; period: number } | null {
  for (const animation of dot.getAnimations()) {
    if (!(animation instanceof CSSAnimation)) continue;
    const timing = animation.effect?.getComputedTiming();
    const phase = timing?.progress;
    const period = timing?.duration;
    if (typeof phase !== "number" || typeof period !== "number" || period <= 0) {
      continue;
    }
    return { phase, period };
  }
  return null;
}

/**
 * Where on the breath's RISE leg the dot would be standing at `scale` —
 * the inverse of {@link breathAt}, restricted to the leg that has one.
 *
 * Used to start the loop at the phase that matches the pose already on screen,
 * as a negative `animation-delay`, so entering `running` picks the settled dot
 * up rather than snapping it to the trough. The rise is the right leg to invert
 * on: a glyph that starts working should be on its way up.
 *
 * Clamped just short of {@link IGNITION} so the loop never begins inside a
 * pulse. Only one pose in the ladder reaches that clamp — a `paused` dot at the
 * small treatment, which sits at full scale — and there the clamp costs about a
 * thousandth of the dot's diameter. Past it the cost would be a ring appearing
 * from nowhere at near-full opacity, which is the pop this function exists to
 * avoid, arriving by another door.
 */
function breathPhaseFor(scale: number, scaleMin: number): number {
  const span = 1 - scaleMin;
  const value =
    span <= 0 ? 0 : Math.min(1, Math.max(0, (scale - scaleMin) / span));
  const phase = (DEFAULT_BREATH_TURN * Math.acos(1 - 2 * value)) / Math.PI;
  return Math.max(0, Math.min(phase, IGNITION - 0.005));
}

/**
 * Stop emitting — but not before the pulse in flight has finished flying.
 *
 * **Once a pulse is lit it always completes.** It is a thing the glyph shed: it
 * left the dot, it is travelling outward under its own momentum, and the work
 * ending has no bearing on it. Cutting it mid-travel is the most visible tear a
 * state change can make, because the eye is already tracking a moving object.
 *
 * So the emitter is released on the pulse's clock rather than the state's. The
 * animation keeps running to the end of its current iteration and the attribute
 * is dropped after it, by which point the ring has faded to nothing and there
 * is nothing left to see go. A pulse that was never lit — the change landed
 * during the inhale, before {@link IGNITION} — is dropped immediately; there is
 * no gesture in progress to honor, and holding the gate open would only let one
 * more ring out of a glyph that has already stopped working.
 */
function releaseEmitter(
  root: HTMLElement,
  ring: HTMLElement,
  timer: React.MutableRefObject<number | null>,
  onReleased?: () => void,
): void {
  if (timer.current !== null) {
    window.clearTimeout(timer.current);
    timer.current = null;
  }
  let remaining = 0;
  for (const animation of ring.getAnimations()) {
    // Keyframe loops only: a transition's progress has nothing to do with
    // where the pulse is, and counting one held the emitter open on a glyph
    // that never lit a ring.
    if (!(animation instanceof CSSAnimation)) continue;
    // The breath runs on the dot span whenever the glyph runs; only the
    // ring's own loops say anything about whether a pulse is in flight.
    const timing = animation.effect?.getComputedTiming();
    const progress = timing?.progress;
    const duration = typeof timing?.duration === "number" ? timing.duration : 0;
    if (typeof progress !== "number" || duration <= 0) continue;
    if (progress < IGNITION) continue;
    remaining = Math.max(remaining, (1 - progress) * duration);
  }
  if (remaining <= 0) {
    delete root.dataset.emitting;
    onReleased?.();
    return;
  }
  timer.current = window.setTimeout(() => {
    timer.current = null;
    delete root.dataset.emitting;
    onReleased?.();
  }, remaining + EMIT_RELEASE_SLACK);
}

/** Settled states paint a reduced dot; held / canceled keep it full-size. */
function isQuiet(state: TugProgressIndicatorState): boolean {
  return state === "stopped" || state === "completed";
}

const IDLE_DOT_SCALE = 0.85;

/**
 * The PRESENCE ladder — how much of the reserved glyph box each state
 * occupies.
 *
 * Size is this variant's whole argument: it exists to be read across a room.
 * But "big" is only legible as a signal if it is *relative*, and the earlier
 * cut had it backwards — every settled state painted a full-box static ring,
 * so a finished session drew a bigger figure than a working one. A row of
 * sessions read as loudest where nothing was happening.
 *
 * So presence became a property of the state, not a constant. `running` is
 * absent from the ladder because it has no static pose to scale: its breath
 * and its emitted ring are authored against the full box and own it outright
 * (see {@link presenceScale}). Every other state is a pose the component seeds,
 * and each one draws in from that edge by the amount below — a held or aborted
 * session stays substantial because it still wants an answer; a stopped or
 * completed one recedes to a quiet marker.
 *
 * The box itself never changes, so the ladder is pure appearance: rows do not
 * reflow as a session moves through it, and a caller's `size` still means the
 * space to reserve.
 *
 * These are the values at full strength. Below 28px the ladder compresses
 * toward 1, and by 16px it is gone — see {@link presenceScale}.
 */
const SETTLED_PRESENCE: Record<
  Exclude<TugProgressIndicatorState, "running">,
  number
> = {
  paused: 0.7,
  aborted: 0.7,
  stopped: 0.5,
  completed: 0.5,
};

/**
 * This state's share of the glyph box, at this size.
 *
 * The ladder ({@link SETTLED_PRESENCE}) is an affordance of the big treatment,
 * and only of it. It encodes state as *relative* size, which needs enough
 * pixels for the relation to be visible — a `completed` 12px glyph on the full
 * ladder is a 6px ring around a 2.5px dot, which is not a quiet marker but an
 * illegible one. So the ladder ramps out with {@link smallness}: gone entirely
 * at 16px and below, where every state owns its box exactly as it did under the
 * previous glyph, and the difference between states is carried by tone and by
 * whether the ring is moving. Those two read at 10px. Size does not.
 */
function presenceScale(state: TugProgressIndicatorState, size: number): number {
  if (state === "running") return 1;
  const base = SETTLED_PRESENCE[state];
  return base + (1 - base) * smallness(size);
}

/**
 * The scale a settled dot rests at — the presence rung, quieted further for
 * the quiet states. `running` resolves to 1 (full box), which is also the
 * pose a promotion seeds a crossing INTO running from.
 */
function settledScaleFor(
  state: TugProgressIndicatorState,
  size: number,
): number {
  return (isQuiet(state) ? IDLE_DOT_SCALE : 1) * presenceScale(state, size);
}

/**
 * Slack on the demotion's duration fallback, in ms. The fallback exists for
 * a `transitionend` that never comes — a zero-duration settle (motion-off
 * resolves the duration to 0) or a settled→settled change that lands on an
 * identical pose (no computed change, no transition, no event). Generous for
 * the same reason {@link EMIT_RELEASE_SLACK} is: a late swap is free.
 */
const DEMOTE_SETTLE_SLACK = 80;

/**
 * The dot's settle duration as the engine resolved it, in ms — never the
 * authored token. Under motion-off (or any `--tug-timing` scaling) the
 * resolved value is what actually elapses, so the demotion window collapses
 * or stretches with it instead of guessing.
 */
function resolvedSettleMs(dot: HTMLElement): number {
  const first = getComputedStyle(dot).transitionDuration.split(",")[0].trim();
  const value = Number.parseFloat(first);
  if (!Number.isFinite(value)) return 0;
  return first.endsWith("ms") ? value : value * 1000;
}

export interface TugProgressPulsingDotProps {
  /** Glyph box diameter in CSS px. @default 32 */
  size?: number;
  /** Lifecycle state. @default "running" */
  state?: TugProgressIndicatorState;
  /** When true, opacity dims. */
  disabled?: boolean;
  /** Additional CSS class names. */
  className?: string;
}

export const TugProgressPulsingDot = React.forwardRef<
  HTMLSpanElement,
  TugProgressPulsingDotProps
>(function TugProgressPulsingDot(
  { size = DEFAULT_SIZE, state = "running", disabled = false, className },
  forwardedRef,
) {
  // The two treatments and everything derived from the size ([sizeGeometry]).
  const { ratio, reach, scaleMin, birth } = sizeGeometry(size);
  // The dot's box is its full-scale diameter; the breath scales it down
  // from there, so the running glyph never grows past the box.
  const dotSizePx = size * ratio;
  // The state's share of the box ([SETTLED_PRESENCE]). Published as a variable
  // so the static ring can size itself from it in CSS without a second source
  // of truth — and so it sizes by WIDTH rather than a transform, which keeps
  // the ring's stroke the same weight at every rung of the ladder.
  const presence = presenceScale(state, size);
  // The period jitter is NOT drawn here — it belongs to the item, and one item
  // can render two glyphs. See [dotDriftFor].
  // The pose the dot rests at once it has settled, drawn in by the state's
  // presence. In live mode it is written to the DOM by the controller below
  // rather than rendered, because a state change has to CROSS to it from
  // wherever the breath left the dot — and React cannot see that pose, only
  // this one. In static mode the SAME number renders as a width/height
  // factor through the `--…-static-scale` variable, a channel with no
  // transform and no transition.
  const staticScale = settledScaleFor(state, size);

  const rootStyle: React.CSSProperties = {
    ["--tugx-progress-pulsing-dot-size" as string]: `${size}px`,
    ["--tugx-progress-pulsing-dot-dot-size" as string]: `${dotSizePx}px`,
    ["--tugx-progress-pulsing-dot-presence" as string]: `${presence}`,
    ["--tugx-progress-pulsing-dot-static-scale" as string]: `${staticScale}`,
    ["--tugx-progress-pulsing-dot-emit-reach-auto" as string]: `${reach.toFixed(4)}`,
    ["--tugx-progress-pulsing-dot-dot-scale-min-auto" as string]: `${scaleMin.toFixed(4)}`,
    ["--tugx-progress-pulsing-dot-emit-birth-auto" as string]: `${birth.toFixed(4)}`,
  };

  // The render mode — the end-state swap. STRUCTURE, so it is React state
  // (see the module header's [L06] note): static renders settled DOM, live
  // renders the loop-and-crossing DOM. Born settled → static, so a restored
  // transcript's dots never touch the motion machinery at all — and the
  // crossing effect's first-paint branch reads that pairing the other way
  // round: live at mount means running.
  const [mode, setMode] = React.useState<"static" | "live">(() =>
    state === "running" ? "live" : "static",
  );

  const rootRef = React.useRef<HTMLSpanElement | null>(null);
  const dotRef = React.useRef<HTMLSpanElement | null>(null);
  const ringRef = React.useRef<HTMLSpanElement | null>(null);
  // The state currently ON SCREEN, which lags the prop for as long as the
  // crossing takes. Held in a ref, not state: it is read to decide what the
  // crossing IS, and it must never provoke a render [L06].
  const shownRef = React.useRef<TugProgressIndicatorState | null>(null);
  const emitTimerRef = React.useRef<number | null>(null);
  // The pending live→static demotion, if one is armed. Cancelling abandons
  // the window; the effect re-arms when appropriate.
  const demotionRef = React.useRef<{ cancel(): void } | null>(null);
  // Where work blocked on a pulse in flight parks its continuation — a pending
  // demotion, or a breath waiting to start welded to a free emitter. The
  // emitter release invokes it (see releaseEmitter's onReleased).
  const emitReleasedRef = React.useRef<(() => void) | null>(null);

  const setRootRef = React.useCallback(
    (node: HTMLSpanElement | null) => {
      rootRef.current = node;
      if (typeof forwardedRef === "function") forwardedRef(node);
      else if (forwardedRef)
        (
          forwardedRef as React.MutableRefObject<HTMLSpanElement | null>
        ).current = node;
    },
    [forwardedRef],
  );

  /**
   * Cross to `state` from whatever is on screen, and run the end-state swap.
   *
   * There are three crossings and each is smooth for its own reason:
   *
   *   - **into a settled state** — the breath is caught in the act. Its live
   *     scale is pinned inline, the loop is dropped against that pin so the
   *     removal changes nothing, and the transition then runs from there.
   *     Meanwhile the shed pulse finishes on its own clock ({@link
   *     releaseEmitter}) and the static ring fades in over it.
   *   - **into `running`** — the loop starts at the phase whose pose the dot is
   *     already standing at ({@link breathPhaseFor}), as a negative delay. The
   *     breath picks the dot up mid-stride. If the settle's own pulse is still
   *     in the air the breath goes anyway and the emitter rejoins its clock
   *     once the pulse lands ({@link rejoinEmitter}).
   *   - **between two settled states** — a plain property change; the dot's
   *     CSS transition carries it, along with the ring's diameter and the tint.
   *
   * Static mode adds the bookends. A state change arriving on a static glyph
   * promotes it to live FIRST (the setState flushes and this effect re-runs
   * before the frame paints), and the live pass seeds the dot's inline pose
   * to exactly what the static DOM was painting — so the crossing starts
   * from there, indistinguishable from a crossing between two live poses.
   * Every crossing that lands in a settled state arms a demotion, which
   * fires only when the full settled predicate holds ({@link armDemotion}):
   * swap when settled, never before.
   *
   * A layout effect, so the DOM is correct before the frame is painted: run
   * after paint and every crossing would show one frame of the wrong pose,
   * which is the tear in miniature.
   */
  React.useLayoutEffect(() => {
    const root = rootRef.current;
    const dot = dotRef.current;
    const ring = ringRef.current;
    if (!root || !dot || !ring) return;

    // Any effect run supersedes a pending demotion: a newer state abandons
    // the window (re-armed below when still appropriate), and a completed
    // demotion's own run clears the spent machinery.
    demotionRef.current?.cancel();
    demotionRef.current = null;
    emitReleasedRef.current = null;

    const previous = shownRef.current;
    const isRunning = state === "running";

    if (mode === "static") {
      // Static mode has no script: the render IS the settled pose. What
      // happens here is arrival bookkeeping and the exit.
      if (dot.style.transform !== "") {
        // Just demoted from live: strip the live-mode inline machinery
        // before this frame paints. [data-static] already declares
        // `transform: none` and `transition: none`, so the strip changes
        // no computed value and can fire nothing.
        dot.style.transform = "";
        dot.style.transition = "";
        root.style.removeProperty(PHASE_VAR);
        root.style.removeProperty(EMIT_PHASE_VAR);
      }
      if (state === "running" || (previous !== null && state !== previous)) {
        // A crossing arrived on a static glyph. Promote: the live pass
        // right after this render plays the crossing, seeded from the
        // static pose. `shownRef` deliberately keeps the OLD state so
        // that pass knows what it is crossing from.
        setMode("live");
        return;
      }
      shownRef.current = state;
      return;
    }

    shownRef.current = state;

    /**
     * Start the breath and the emitter — TOGETHER, which is the only way they
     * are one clock.
     *
     * The phase lock is not a property of the durations; it is a property of
     * the two loops having the same start time, and they only get that by
     * being gated on in the same style flush. Writing an attribute that is
     * ALREADY on the element is not a change and starts nothing, so a glyph
     * that arrives here with one gate still open would restart the other
     * against a loop already in progress — and then the ring sheds its pulse
     * at some arbitrary point in the breath for the rest of the run.
     *
     * So both gates are closed and the removal is FLUSHED before either is
     * opened, whenever either is already set. Restarting a loop at the phase it
     * is already standing at costs at most the frame in between, which is a
     * stall too small to see; starting two loops a quarter cycle apart is
     * permanent and unrecoverable.
     */
    const startLoops = (phase: number): void => {
      if (emitTimerRef.current !== null) {
        window.clearTimeout(emitTimerRef.current);
        emitTimerRef.current = null;
      }
      if (
        root.dataset.breathing !== undefined ||
        root.dataset.emitting !== undefined
      ) {
        delete root.dataset.breathing;
        delete root.dataset.emitting;
        void root.offsetWidth;
      }
      root.style.setProperty(PHASE_VAR, `${-phase}`);
      root.style.setProperty(EMIT_PHASE_VAR, `${-phase}`);
      root.dataset.breathing = "";
      root.dataset.emitting = "";
    };

    /**
     * Start the breath alone, leaving a pulse already in the air untouched.
     *
     * Only the resume-mid-pulse case calls this, and only because the ring is
     * unavailable: it is still running out the pulse the last settle shed, and
     * that pulse always finishes. Waiting for it would cost the dot the thing
     * the phase match buys — the breath picking it up where it stood — for the
     * better part of a cycle, on what is the ordinary way work resumes. So the
     * dot goes back to breathing at once and the emitter rejoins it after
     * ({@link rejoinEmitter}).
     */
    const startBreath = (phase: number): void => {
      root.style.setProperty(PHASE_VAR, `${-phase}`);
      root.dataset.breathing = "";
    };

    /**
     * Put the emitter back on the breath's clock.
     *
     * Called once the shed pulse has landed. The rejoin is a restart of BOTH
     * loops from where the breath currently stands — the only way they end up
     * sharing a start time, and invisible on the dot's side because the breath
     * resumes at its own phase.
     *
     * It waits for the breath to be somewhere in its INHALE first. The ring's
     * loop paints a mid-flight pulse at any phase past ignition, so rejoining
     * there would put a half-faded ring on screen out of nothing — the pop that
     * running the pulse out to its end was avoiding. Before ignition the ring is
     * parked at the dot's edge and fully faded, which is exactly what it is
     * already showing, so the rejoin paints nothing at all.
     */
    const rejoinEmitter = (): void => {
      const clock = breathClock(dot);
      // No breath to rejoin: a newer crossing has taken the glyph, and it owns
      // the loops now.
      if (clock === null) return;
      if (clock.phase >= IGNITION) {
        emitTimerRef.current = window.setTimeout(
          rejoinEmitter,
          (1 - clock.phase) * clock.period + EMIT_RELEASE_SLACK,
        );
        return;
      }
      startLoops(clock.phase);
    };

    /**
     * A running glyph's emitter is flying, or on its way back. Never neither.
     *
     * The rejoin is carried across renders by two refs, and a render can land
     * in the middle of it — a size change, a role change, a parent re-render.
     * This re-establishes the continuation on every pass rather than trusting
     * the one that armed it to still be reachable, because the state it is
     * guarding against is a dot that breathes and never sheds a ring again.
     */
    const ensureEmitter = (): void => {
      if (emitTimerRef.current !== null) {
        emitReleasedRef.current = rejoinEmitter;
        return;
      }
      if (root.dataset.emitting !== undefined) return;
      rejoinEmitter();
    };

    /**
     * Arm the live→static demotion — the SWAP WHEN SETTLED rule. All
     * clauses required, in order:
     *
     *   1. state agreement — guaranteed by construction: any newer state
     *      re-runs this effect, which cancels the pending window first
     *      thing;
     *   2. the dot's settle transition has completed — `transitionend`
     *      for `transform`, with a resolved-duration fallback for the
     *      events that never come (motion-off resolves the duration to 0;
     *      an identical-pose change fires no transition at all);
     *   3. no pulse in flight — `data-emitting` absent. A lit ring always
     *      finishes its travel on its own clock; the emitter release
     *      re-invokes the check however long after the dot landed;
     *   4. nothing else animating under the root — catches the static
     *      ring's fade and the tint crossings, which run their own
     *      transitions on separate boxes;
     *   5. one frame of grace, so the swap replaces DOM that has painted
     *      its final pose with DOM that paints the identical pose.
     *
     * Everything here is event-driven and runs a handful of times per
     * state change — never per frame. Late is free; early is a glitch.
     */
    const armDemotion = (): void => {
      let cancelled = false;
      let grace = 0;
      const settle = () => {
        if (cancelled) return;
        if (root.dataset.emitting !== undefined) {
          emitReleasedRef.current = settle;
          return;
        }
        const running = root
          .getAnimations({ subtree: true })
          .filter((animation) => animation.playState === "running");
        if (running.length > 0) {
          void Promise.allSettled(
            running.map((animation) => animation.finished),
          ).then(() => {
            if (!cancelled) settle();
          });
          return;
        }
        grace = requestAnimationFrame(() => {
          if (cancelled) return;
          setMode("static");
        });
      };
      const onTransitionEnd = (event: TransitionEvent): void => {
        if (event.target === dot && event.propertyName === "transform") {
          settle();
        }
      };
      dot.addEventListener("transitionend", onTransitionEnd);
      const fallback = window.setTimeout(
        settle,
        resolvedSettleMs(dot) + DEMOTE_SETTLE_SLACK,
      );
      demotionRef.current = {
        cancel() {
          cancelled = true;
          dot.removeEventListener("transitionend", onTransitionEnd);
          window.clearTimeout(fallback);
          if (grace !== 0) cancelAnimationFrame(grace);
        },
      };
    };

    // First paint in live mode, which means born RUNNING: the mode
    // initializer derives `static` from the same `state` this effect reads,
    // so a dot born settled never reaches here — it is static's business.
    // Nothing to cross from, so the full pose and the loops are seeded
    // directly — with the transition suppressed around the write. There is
    // nothing this could visibly transition FROM, so letting it fire buys
    // only a wasted style pass, and WebKit retains the finished
    // CSSTransition in getAnimations() forever — one zombie per dot,
    // iterated by the animation controller on every rendering update.
    // Whether it fires depends on whether anything flushed style between
    // the insertion and this effect, so the suppression is unconditional.
    if (previous === null) {
      dot.style.transition = "none";
      dot.style.transform = dotPose(1);
      void dot.offsetWidth;
      dot.style.transition = "";
      startLoops(0);
      return;
    }

    // Just promoted from static: the render dropped [data-static], whose
    // rules were carrying the pose, and the dot holds no inline transform.
    // Seed the pose the static DOM was painting — suppressed, it IS that
    // pose — so the crossing below starts from exactly there.
    if (dot.style.transform === "") {
      dot.style.transition = "none";
      dot.style.transform = dotPose(settledScaleFor(previous, size));
      void dot.offsetWidth;
      dot.style.transition = "";
    }

    if (previous === "running" && !isRunning) {
      const live = liveScale(dot);
      if (live !== null) {
        dot.style.transition = "none";
        dot.style.transform = dotPose(live);
      }
      delete root.dataset.breathing;
      // Flush the pin while the transition is suppressed, so dropping the loop
      // resolves to the same pose it was already painting instead of firing a
      // transition from the keyframe's base value.
      void dot.offsetWidth;
      dot.style.transition = "";
      dot.style.transform = dotPose(staticScale);
      releaseEmitter(root, ring, emitTimerRef, () =>
        emitReleasedRef.current?.(),
      );
      armDemotion();
      return;
    }

    if (previous !== "running" && isRunning) {
      const live = liveScale(dot);
      const phase = live === null ? 0 : breathPhaseFor(live, scaleMin);
      // Work resuming while the last settle's pulse is still in the air — the
      // ordinary way work resumes, since a pulse travels most of a cycle. Two
      // of the glyph's rules apply here and they point opposite ways: a lit
      // pulse always finishes its travel, and the two loops are only welded if
      // they START together, which they cannot do while one of them is still
      // running out a pulse the other has nothing to do with.
      //
      // Neither rule gives way. The breath starts now, on its own variable so
      // the flying ring is undisturbed, and the emitter rejoins it on the
      // pulse's own clock.
      if (root.dataset.emitting !== undefined && emitTimerRef.current !== null) {
        startBreath(phase);
        ensureEmitter();
        return;
      }
      startLoops(phase);
      return;
    }

    dot.style.transform = dotPose(isRunning ? 1 : staticScale);
    if (isRunning) ensureEmitter();
    else armDemotion();
  }, [state, staticScale, scaleMin, mode, size]);

  React.useEffect(
    () => () => {
      if (emitTimerRef.current !== null)
        window.clearTimeout(emitTimerRef.current);
      demotionRef.current?.cancel();
    },
    [],
  );

  return (
    <span
      ref={setRootRef}
      data-slot="tug-progress-pulsing-dot"
      data-state={state}
      data-static={mode === "static" ? "" : undefined}
      aria-hidden="true"
      style={rootStyle}
      className={cn(
        "tug-progress-pulsing-dot",
        disabled && "tug-progress-pulsing-dot-disabled",
        className,
      )}
    >
      <span ref={dotRef} className="tug-progress-pulsing-dot-dot" />
      {/* The emitted pulse. Its stroke opens as it travels, because a border on
          a scaled element paints at border × scale. */}
      <span ref={ringRef} className="tug-progress-pulsing-dot-ring" />
    </span>
  );
});
