/**
 * menus-doc.ts — regenerate `tuglaws/menus.md`'s tables from the registry.
 *
 * `menus.md` used to hand-maintain a catalog of control frames and a table of
 * chords. Both drifted, in twelve separate ways, because a doc table and a
 * code table are two spellings of one fact and only one of them is executed.
 * These generators make the doc's two derived sections a projection instead:
 * the test beside this file regenerates them and diffs against what is
 * checked in, so the catalog cannot fall behind the table that ships.
 *
 * The generated regions are delimited in the doc by HTML comments. Everything
 * outside them is prose, written by hand, and this module never touches it —
 * a doc that regenerated its own argument would be a doc nobody wrote.
 */

import { COMMANDS } from "../command-registry";
import type { CommandEntry } from "../command-registry";
import { KeymapRegistry } from "../keymap-registry";
import { formatChord } from "../chord-format";

/** Opening marker for a generated region. */
export function beginMarker(name: string): string {
  return `<!-- generated:${name} — regenerated by menus-doc.test.ts; do not hand-edit -->`;
}

/** Closing marker for a generated region. */
export function endMarker(name: string): string {
  return `<!-- /generated:${name} -->`;
}

/** Replace a named generated region's body, keeping the markers. */
export function spliceRegion(doc: string, name: string, body: string): string {
  const begin = beginMarker(name);
  const end = endMarker(name);
  const from = doc.indexOf(begin);
  const to = doc.indexOf(end);
  if (from < 0 || to < 0) throw new Error(`menus-doc: no ${name} region in the doc`);
  return `${doc.slice(0, from + begin.length)}\n${body}\n${doc.slice(to)}`;
}

/** Read a named generated region's body. */
export function readRegion(doc: string, name: string): string {
  const begin = beginMarker(name);
  const end = endMarker(name);
  const from = doc.indexOf(begin);
  const to = doc.indexOf(end);
  if (from < 0 || to < 0) throw new Error(`menus-doc: no ${name} region in the doc`);
  return doc.slice(from + begin.length, to).trim();
}

/** How a routing value reads in prose. */
const ROUTING_PROSE: Readonly<Record<string, string>> = {
  "first-responder": "first responder",
  "key-card": "key card",
  target: "targeted control",
  registry: "registered handler",
  native: "AppKit performs it",
};

function escapePipes(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/**
 * The catalog: every command the host can send, what drives it, and where it
 * lands. One row per registry entry that names a menu item — those are
 * exactly the commands a menu can send — plus the parameterized families,
 * which have menu items built at rebuild time rather than stated here.
 */
export function generateCatalog(entries: readonly CommandEntry[] = COMMANDS): string {
  const rows = entries
    .filter((e) => e.menuItemId !== undefined)
    .sort((a, b) => (a.menuItemId as string).localeCompare(b.menuItemId as string))
    .map((e) => {
      const routing = ROUTING_PROSE[e.routing] ?? e.routing;
      const gate = e.mirrored === true ? "registry gate" : "host tier";
      return `| \`${e.menuItemId}\` | \`${escapePipes(e.id)}\` | ${routing} | ${gate} |`;
    });
  return [
    "| Menu item | Command | Routing | Enablement |",
    "|---|---|---|---|",
    ...rows,
  ].join("\n");
}

/**
 * The chord table: every chord the table states, what it runs, and whether
 * the menu bar takes it before the web view can.
 */
export function generateChordTable(entries: readonly CommandEntry[] = COMMANDS): string {
  const registry = new KeymapRegistry(entries);
  const rows: string[] = [];
  for (const entry of entries) {
    for (const binding of registry.bindingsOf(entry.id)) {
      // Where the chord is actually taken. A `native` command's item carries
      // the chord as a construction literal and AppKit performs it, so
      // reporting its binding as a JS claim would be exactly backwards — the
      // entry exists so the keymap UI can *show* the chord, not route it.
      const layer =
        entry.routing === "native"
          ? "menu bar (AppKit's own)"
          : binding.menuEligible === true
            ? "menu bar (swept)"
            : binding.scope.kind === "global"
              ? "JS, global"
              : `JS, ${binding.scope.kind}`;
      rows.push(
        `| ${formatChord(binding.chord)} | \`${escapePipes(entry.id)}\` | ${escapePipes(entry.title)} | ${layer} |`,
      );
    }
  }
  rows.sort();
  return [
    "| Chord | Command | Title | Claimed at |",
    "|---|---|---|---|",
    ...rows,
  ].join("\n");
}
