#!/usr/bin/env bun
/**
 * generate-tug-tokens.ts
 *
 * Generates ALL --tug-* tokens for every built-in theme recipe.
 *
 * Brio (default dark):
 *   styles/tug-base-generated.css — imported by tug-base.css via @import.
 *   Contains bare custom property declarations (2-space indent) inside
 *   the body {} context of tug-base.css.
 *
 * Non-default themes (e.g. harmony):
 *   styles/themes/<name>.css — standalone override files. Each file wraps
 *   all 373 tokens in a body {} block. When injected as a <style> element
 *   after tug-base.css, the cascade overrides all brio defaults. [D01]
 *
 * Also emits:
 *   src/generated/theme-canvas-params.ts — static THEME_CANVAS_PARAMS map
 *   for production use (no server-side derivation at runtime). [D08]
 *
 * Usage:
 *   bun run scripts/generate-tug-tokens.ts
 *
 * Or via package.json:
 *   bun run generate:tokens
 *   bun run generate:control-tokens  (alias for backward compat)
 */

import path from "path";
import { mkdir } from "fs/promises";
import type { ThemeRecipe } from "../src/components/tugways/theme-engine";
import { deriveTheme } from "../src/components/tugways/theme-engine";
import { generateThemeCSS } from "../src/theme-css-generator";
import { BASE_THEME_NAME } from "../src/theme-constants";

const tugdeckDir = path.resolve(import.meta.dir, "..");
const themesJsonDir = path.join(tugdeckDir, "themes");
const themesDir = path.join(tugdeckDir, "styles", "themes");
const generatedSrcDir = path.join(tugdeckDir, "src", "generated");

// ---------------------------------------------------------------------------
// Discover all theme JSON files via Bun's built-in glob
// ---------------------------------------------------------------------------

const glob = new Bun.Glob("*.json");
const themeFiles = (await Array.fromAsync(glob.scan({ cwd: themesJsonDir }))).sort();

if (themeFiles.length === 0) {
  console.error("[generate-tug-tokens] No theme JSON files found in", themesJsonDir);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Generate CSS for each discovered theme and collect canvas params
// ---------------------------------------------------------------------------

/** Canvas color params for the static THEME_CANVAS_PARAMS map. */
interface CanvasParams {
  hue: string;
  tone: number;
  intensity: number;
}

const canvasParamsMap: Record<string, CanvasParams> = {};

/** The full ThemeRecipe for the base theme, captured for BASE_THEME_RECIPE export. */
let baseThemeRecipe: ThemeRecipe | null = null;

for (const themeFileName of themeFiles) {
  const themeFilePath = path.join(themesJsonDir, themeFileName);
  const recipe = (await Bun.file(themeFilePath).json()) as ThemeRecipe;
  const css = generateThemeCSS(recipe);
  const tokenCount = (css.match(/--tug-/g) ?? []).length;

  // Derive canvas params for the static production map.
  const themeOutput = deriveTheme(recipe);
  canvasParamsMap[recipe.name] = {
    hue: recipe.surface.canvas.hue,
    tone: themeOutput.formulas.surfaceCanvasTone,
    intensity: themeOutput.formulas.surfaceCanvasIntensity,
  };

  if (recipe.name === BASE_THEME_NAME) {
    // Base theme — write to tug-base-generated.css
    baseThemeRecipe = recipe;
    const generatedCssPath = path.join(tugdeckDir, "styles", "tug-base-generated.css");
    await Bun.write(generatedCssPath, css);
    console.log(
      `[generate-tug-tokens] wrote ${tokenCount} tokens to ${generatedCssPath}`,
    );
  } else {
    // Non-base themes — write to styles/themes/<name>.css
    const themeCssPath = path.join(themesDir, `${recipe.name}.css`);
    await Bun.write(themeCssPath, css);
    console.log(
      `[generate-tug-tokens] wrote ${tokenCount} tokens to ${themeCssPath}`,
    );
  }
}

// ---------------------------------------------------------------------------
// Emit THEME_CANVAS_PARAMS static map to src/generated/theme-canvas-params.ts
// ---------------------------------------------------------------------------

await mkdir(generatedSrcDir, { recursive: true });

const entries = Object.entries(canvasParamsMap)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, p]) => `  ${JSON.stringify(name)}: { hue: ${JSON.stringify(p.hue)}, tone: ${p.tone}, intensity: ${p.intensity} },`)
  .join("\n");

const canvasParamsTs = `/**
 * theme-canvas-params.ts — GENERATED, DO NOT EDIT.
 *
 * Static map of canvas color params for all shipped themes.
 * Generated by scripts/generate-tug-tokens.ts. Used by theme-provider.tsx
 * in production mode (no Vite dev server) to skip the POST /__themes/activate
 * round-trip and derive canvas color without runtime derivation. [D08]
 *
 * Re-generate with: bun run generate:tokens
 */

import type { CanvasColorParams } from "../canvas-color";

export const THEME_CANVAS_PARAMS: Record<string, CanvasColorParams> = {
${entries}
};
`;

const canvasParamsTsPath = path.join(generatedSrcDir, "theme-canvas-params.ts");
await Bun.write(canvasParamsTsPath, canvasParamsTs);
console.log(`[generate-tug-tokens] wrote THEME_CANVAS_PARAMS map to ${canvasParamsTsPath}`);

// ---------------------------------------------------------------------------
// Emit BASE_THEME_RECIPE to src/generated/base-theme-recipe.ts
// ---------------------------------------------------------------------------

if (baseThemeRecipe === null) {
  console.error(`[generate-tug-tokens] base theme "${BASE_THEME_NAME}" not found — BASE_THEME_RECIPE not emitted`);
  process.exit(1);
}

const baseThemeRecipeTs = `/**
 * base-theme-recipe.ts — GENERATED, DO NOT EDIT.
 *
 * The full ThemeRecipe for the base theme (${BASE_THEME_NAME}).
 * Generated by scripts/generate-tug-tokens.ts.
 *
 * Used by main.tsx at startup to derive canvas params without importing
 * theme JSON directly. Re-generate with: bun run generate:tokens
 */

import type { ThemeRecipe } from "../components/tugways/theme-engine";

export const BASE_THEME_RECIPE: ThemeRecipe = ${JSON.stringify(baseThemeRecipe, null, 2)} as const;
`;

const baseThemeRecipeTsPath = path.join(generatedSrcDir, "base-theme-recipe.ts");
await Bun.write(baseThemeRecipeTsPath, baseThemeRecipeTs);
console.log(`[generate-tug-tokens] wrote BASE_THEME_RECIPE to ${baseThemeRecipeTsPath}`);
