/**
 * Decoded event union consumed by the `CodeSessionStore` reducer.
 *
 * Step 3 populates the core stream-json types driving the basic turn
 * round-trip plus the internal `send` action; later steps add
 * `thinking_text` (Step 4), tool events (Step 5),
 * `control_request_forward` / `cost_update` / respond actions (Step 6),
 * `interrupt` (Step 7), and `session_state_errored` / `transport_close`
 * (Step 8). The Step 1 `__noop__` placeholder is gone — every event now
 * carries a real type.
 */

import type { AtomSegment } from "../tug-atom-img";
import type { ControlRequestForward } from "./types";

/** Internal `send` action injected by `CodeSessionStore.send`. */
export interface SendActionEvent {
  type: "send";
  text: string;
  atoms: AtomSegment[];
  /**
   * Stable per-turn React-key seed, generated by the store wrapper
   * before dispatch (the reducer is pure and must not call
   * `crypto.randomUUID()` itself). Threaded onto `pendingUserMessage`
   * by `handleSend` and preserved through `handleTurnComplete` onto
   * the committed `TurnEntry`. See `TurnEntry.turnKey` for the
   * cell-stability invariant this drives.
   */
  turnKey: string;
}

/** `session_init` frame — carries Claude's `session_id` (for `--resume`). */
export interface SessionInitEvent {
  type: "session_init";
  session_id?: string;
  tug_session_id?: string;
  [key: string]: unknown;
}

/** Decoded assistant_text partial or terminal frame. `block_index`
 *  correlates the delta with its opening `content_block_start` via
 *  the wire's `(msg_id, block_index)` coordinate ([D07]). Required —
 *  every text frame tugcode emits after Step 5 carries it.
 */
export interface AssistantTextEvent {
  type: "assistant_text";
  msg_id: string;
  block_index: number;
  text: string;
  is_partial: boolean;
  rev?: number;
  seq?: number;
  tug_session_id?: string;
  [key: string]: unknown;
}

/** Decoded thinking_text partial or terminal frame. See
 *  {@link AssistantTextEvent} for the `block_index` correlation
 *  contract. */
export interface ThinkingTextEvent {
  type: "thinking_text";
  msg_id: string;
  block_index: number;
  text: string;
  is_partial: boolean;
  rev?: number;
  seq?: number;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `content_block_start` — wire-derived block-open marker emitted by
 * tugcode at every Claude `content_block_start` event ([D07]). Mints
 * a new `Message` of the given `kind` keyed by `(msg_id, block_index)`
 * in the reducer's `scratch[turnKey].blockIndex` map.
 *
 * Idempotent at the reducer: re-emitting the same `(msg_id, block_index)`
 * is a no-op. This is what makes the mid-turn replay snapshot pattern
 * (Option 4 in [D07]) safe — the snapshot replays the full event
 * stream including the `content_block_start` events the live path
 * already consumed; the reducer mints once and the snapshot's repeat
 * is inert.
 *
 * `tool_use_id` and `tool_name` are required on the `tool_use` kind
 * (the substrate needs them to construct the `ToolUseMessage`); the
 * other kinds omit them.
 */
export interface ContentBlockStartEvent {
  type: "content_block_start";
  msg_id: string;
  block_index: number;
  kind: "text" | "thinking" | "tool_use";
  tool_use_id?: string;
  tool_name?: string;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `tool_use` — Claude opens or updates a tool call. The first event
 * for a logical call arrives with `input: {}`; a second `tool_use` with
 * the same `tool_use_id` carries the filled-in input.
 *
 * `parent_tool_use_id` is set when this call was made *by a subagent*
 * — it points at the spawning `Agent` tool call's `tool_use_id`. The
 * reducer records it on the `ToolCallState` so the rendering layer can
 * nest a subagent's intermediate tool calls under its
 * `AgentTranscriptBlock` instead of rendering them as flat siblings
 * ([#step-17-5]).
 */
export interface ToolUseEvent {
  type: "tool_use";
  msg_id?: string;
  tool_use_id: string;
  tool_name: string;
  input: unknown;
  seq?: number;
  parent_tool_use_id?: string;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `tool_result` — terminates a logical call. `is_error: true` routes
 * the entry to `status: "error"`; otherwise `status: "done"`. The
 * transition `tool_work → streaming` fires only when every entry in
 * `toolCallMap` is terminal.
 */
export interface ToolResultEvent {
  type: "tool_result";
  tool_use_id: string;
  output?: unknown;
  is_error?: boolean;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `tool_use_structured` — structured result for a prior `tool_result`.
 * Populates `structuredResult` on the matching map entry without
 * changing its terminal status.
 */
export interface ToolUseStructuredEvent {
  type: "tool_use_structured";
  tool_use_id: string;
  tool_name?: string;
  structured_result?: unknown;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `turn_complete` — closes the active turn.
 *
 * `result`:
 *  - `"success"` — the turn finished cleanly (`stop_reason: end_turn`).
 *  - `"error"` — the turn ended on a protocol error.
 *  - `"interrupted"` — an explicit cut-off terminal. tugcode's replay
 *    translator emits this for orphan-interrupted submissions and for
 *    a dangling cold-resume turn (a JSONL cycle with no `end_turn`);
 *    the reducer commits it with `turnEndReason: "interrupted"`.
 *
 * `telemetry` is populated on the replay path only: when the
 * supervisor reads a per-turn telemetry row from the SessionLedger
 * for the matching `msg_id`, it inlines that block onto the replayed
 * `turn_complete` event. Live `turn_complete` events from the wire
 * never carry telemetry — the reducer derives it from in-memory
 * clock anchors + cost snapshots. See `mergeTurnTelemetry` in
 * `telemetry.ts` and the design in plan `#step-20-3-3`.
 */
export interface TurnCompleteEvent {
  type: "turn_complete";
  msg_id: string;
  result: "success" | "error" | "interrupted";
  tug_session_id?: string;
  telemetry?: import("./telemetry").TurnTelemetry;
  [key: string]: unknown;
}

/**
 * `system_metadata` — per [D09], `SessionMetadataStore` owns this feed.
 * The reducer sees the event only to explicitly drop it (so its
 * presence on CODE_OUTPUT stays grep-friendly).
 */
export interface SystemMetadataEvent {
  type: "system_metadata";
  [key: string]: unknown;
}

/**
 * `control_request_forward` — Claude forwards a permission prompt
 * (`is_question: false`) or an `AskUserQuestion` prompt (`is_question:
 * true`). The reducer stashes the previous phase and transitions to
 * `awaiting_approval`; `respondApproval` / `respondQuestion` restore it.
 * The extra fields beyond `type` are preserved on `pendingApproval` /
 * `pendingQuestion` so UI code can read `tool_name`, `options`, etc.
 */
export type ControlRequestForwardEvent = {
  type: "control_request_forward";
} & ControlRequestForward;

/**
 * Internal action injected by `CodeSessionStore.respondApproval`. Not
 * a wire event — never decoded from a frame.
 */
export interface RespondApprovalActionEvent {
  type: "respond_approval";
  request_id: string;
  decision: "allow" | "deny";
  updatedInput?: unknown;
  message?: string;
}

/**
 * Internal action injected by `CodeSessionStore.respondQuestion`. Not
 * a wire event — never decoded from a frame.
 */
export interface RespondQuestionActionEvent {
  type: "respond_question";
  request_id: string;
  answers: Record<string, unknown>;
}

/**
 * Internal action injected by `CodeSessionStore.interrupt`. Not a wire
 * event — never decoded from a frame. The reducer emits an `interrupt`
 * SendFrame effect and clears `queuedSends` per [D05].
 */
export interface InterruptActionEvent {
  type: "interrupt_action";
}

/**
 * Internal action injected by
 * `CodeSessionStore.consumePendingDraftRestore`. Not a wire event. The
 * reducer clears `pendingDraftRestore` to `null` so the prompt-entry
 * editor's `useLayoutEffect` does not re-apply the restore on
 * subsequent snapshot rebuilds. The flow is: CASE A interrupt sets
 * `pendingDraftRestore` → prompt-entry observes the slot via
 * `useSyncExternalStore`, applies it to the editor inside a
 * `useLayoutEffect` keyed on the slot's identity, and dispatches this
 * action. Idempotent — a second consume while the slot is already
 * `null` is a state-ref-stable no-op.
 */
export interface ConsumeDraftRestoreActionEvent {
  type: "consume_draft_restore";
}

/**
 * Internal action injected by `CodeSessionStore.cancelQueuedSend`. Not
 * a wire event. Removes one entry from `queuedSends` by `turnKey` — a
 * true un-send of a mid-turn submission that was queued but never
 * dispatched (no wire traffic, no server turn). The reducer routes the
 * removed entry's `text` + `atoms` through `pendingDraftRestore` so the
 * prompt-entry can offer the prompt back (seeded iff the editor is
 * empty — a cancel never clobbers in-progress content). A no-op if the
 * `turnKey` is no longer queued (it flushed first — a race).
 */
export interface CancelQueuedSendActionEvent {
  type: "cancel_queued_send";
  turnKey: string;
}

/**
 * `context_breakdown` — `/context`-style per-category token breakdown
 * emitted by tugcode at session_init, after each `cost_update`, and
 * after `compact_boundary`. Also emitted by the tugcast supervisor
 * once at bind time from the persisted `context_breakdown_latest`
 * ledger row so the popover renders pre-populated on a fresh bind.
 *
 * The reducer captures the latest frame onto state and projects it
 * onto `CodeSessionSnapshot.lastContextBreakdown`. Each frame also
 * fires a `record-context-breakdown` effect that persists the
 * payload via the supervisor's `record_context_breakdown` CONTROL
 * handler — the round trip is reducer → CONTROL → supervisor →
 * ledger, mirroring the per-turn telemetry path.
 *
 * `categories[]` carries the per-category token counts in the order
 * the renderer paints them. `autocompact_buffer` is conditional;
 * `mcp_tools` is never present (out of scope).
 */
export interface ContextBreakdownEvent {
  type: "context_breakdown";
  tug_session_id?: string;
  context_max: number;
  categories: ReadonlyArray<{
    id: import("./types").ContextBreakdownCategoryId;
    label: string;
    tokens: number;
  }>;
  /**
   * Set to `true` by the tugcast supervisor when it synthesizes this
   * frame from the persisted ledger row at bind time. The reducer
   * uses this flag to suppress the redundant `record-context-breakdown`
   * effect — the row already exists, re-persisting it would write
   * identical bytes back to the same UPSERT slot.
   *
   * Absent on live frames from tugcode (those get persisted as
   * normal). The popover renderer ignores the flag.
   */
  from_supervisor_attach?: boolean;
  [key: string]: unknown;
}

/**
 * `cost_update` — telemetry frame carrying cumulative dollar cost and
 * per-turn/session accounting. Surfaced through the snapshot's
 * `lastCost` field with no phase transition; `cost_update` can land in
 * any phase. Live fixtures also emit `usage` and `modelUsage` trees
 * with token breakdowns — the reducer passes those through as
 * `unknown` for renderers that want them.
 */
export interface CostUpdateEvent {
  type: "cost_update";
  total_cost_usd: number;
  num_turns?: number;
  duration_ms?: number;
  duration_api_ms?: number;
  usage?: unknown;
  modelUsage?: unknown;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `streaming_usage` — live intra-turn token usage emitted by tugcode
 * from the streaming `message_start` / `message_delta` events of the
 * in-flight turn. `usage` is the same four-token shape `cost_update`
 * carries; `msg_id` is claude's `message.id` for the assistant
 * message the usage belongs to.
 *
 * The reducer accumulates these per-message into `liveTurnUsage` with
 * no phase transition and no persistence — a display-only telemetry
 * frame, like `cost_update`. The terminal `cost_update` is
 * authoritative and supersedes the live accumulation at turn-complete.
 */
export interface StreamingUsageEvent {
  type: "streaming_usage";
  msg_id?: string;
  usage?: unknown;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * `error` — a wire-level error frame distinct from SESSION_STATE
 * errored and from transport close. Listed in the outbound event table
 * (design doc) but never captured in v2.1.105 fixtures, so tests
 * exercise it via synthetic dispatch. Routes to the `errored` phase
 * with cause `wire_error`.
 */
export interface WireErrorEvent {
  type: "error";
  message?: string;
  recoverable?: boolean;
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * Transient attachment-rejection error from the drop / paste
 * pipelines. Dispatched by `CodeSessionStore.publishAttachmentError`
 * when `downsampleImage` returns one of its discriminated errors
 * (oversize image, unsupported source format, decode failure).
 *
 * Routes through `state.lastError` with `cause:
 * "attachment_rejected"`. Distinct from wire / session errors — the
 * session stays in its current phase (idle, submitting, …), only the
 * banner surfaces the message. Self-clears on the next successful
 * turn commit.
 *
 * Per [Table T01](../../../roadmap/tide-atoms.md#t01-failure-modes).
 */
export interface AttachmentRejectedEvent {
  type: "attachment_rejected";
  message: string;
}

/**
 * Internal event mapped from a `SESSION_STATE { state: "errored" }`
 * frame. The store's `frameToEvent` extracts the `detail` field from
 * the wire payload; the reducer rolls it into `state.lastError.message`.
 * Only the `"errored"` state maps to an event — all other states
 * (`pending`, `spawning`, `closed`, …) are dropped in `frameToEvent`.
 */
export interface SessionStateErroredEvent {
  type: "session_state_errored";
  detail?: string;
}

/**
 * Internal event injected when `ConnectionLifecycle` fires
 * `connectionDidClose`. Not a wire event — the store subscribes to the
 * lifecycle at construction and dispatches this action per [D06].
 * The reducer always sets `transportState = "offline"`; non-idle
 * phases additionally flip to `errored` and stamp `lastError`.
 */
export interface TransportCloseEvent {
  type: "transport_close";
}

/**
 * Internal event injected when `ConnectionLifecycle` fires
 * `connectionDidReconnect` (or, defensively, an open from any state).
 * The reducer moves `transportState` from `offline` to `restoring`;
 * `transport_settled` is what eventually clears it back to `online`
 * once the per-card binding is re-acked. Per [D08], an open while
 * already `online` is a no-op (state ref unchanged) so duplicate
 * lifecycle dispatches don't churn subscribers.
 */
export interface TransportOpenEvent {
  type: "transport_open";
}

/**
 * Internal event injected by the `cardSessionBindingStore` subscription
 * once the per-card binding is (re-)established. Distinct from
 * `transport_open` because the wire being live does not by itself mean
 * the supervisor has re-acked this card's session — the card stays in
 * `restoring` until the binding lands, then this event flips
 * `transportState` to `online`. Per [D04].
 */
export interface TransportSettledEvent {
  type: "transport_settled";
}

/**
 * Internal event mapped from a CONTROL frame of shape
 * `{ type: "error", detail: "session_unknown", tug_session_id }`.
 * Supervisor emits this when a CODE_INPUT arrives for a session it
 * doesn't know about (orphan dispatcher) — the classic "stale
 * session_id after server reconnect" failure mode. The frame carries
 * `tug_session_id`, so the per-card filter routes it cleanly via the
 * normal session-match path.
 */
export interface SessionUnknownEvent {
  type: "session_unknown";
  detail?: string;
}

/**
 * Internal event mapped from a CONTROL frame of shape
 * `{ type: "error", detail: "session_not_owned" }`. Router's P5 authz
 * check emits this when a client sends CODE_INPUT for a session that
 * another client owns — or, more commonly, a session this client
 * never registered via `spawn_session`. The wire frame currently
 * carries NO `tug_session_id` field (see `router.rs`: the rejection
 * handler sends just `{type, detail}`), so the per-card filter
 * relaxes for CONTROL error frames and the reducer uses a phase gate
 * — only stores in a waiting-for-response phase accept the routing —
 * to self-route in the multi-card single-client case.
 */
export interface SessionNotOwnedEvent {
  type: "session_not_owned";
  detail?: string;
}

/**
 * Emitted by tugcode when a `--session-mode resume` spawn fails.
 * Forwarded by tugcast on the CODE_OUTPUT feed as a normal stream-json
 * message; `CodeSessionStore`'s `acceptFrame` maps it to this event
 * and the reducer rolls it into `lastError` with cause `"resume_failed"`.
 *
 * The store does not change phase on this event — the phase flip to
 * `errored` arrives via the subsequent `session_state_errored` event
 * that the bridge broadcasts after promoting the EOF to a terminal
 * `ResumeFailed` outcome. The card observer reads `lastError.cause`
 * and clears the binding so the picker re-presents with the reason.
 */
export interface ResumeFailedEvent {
  type: "resume_failed";
  /** Machine-readable category (e.g. `"exit"`, `"timeout"`). */
  reason?: string;
  /** The id tugcode attempted to resume. */
  stale_session_id?: string;
}

/**
 * Replay user-message frame emitted by tugcode's JSONL replay
 * translator (cold-boot) and by tugcode's mid-turn snapshot path
 * (`emitInflightTurnFromActiveTurn`). The reducer's
 * `handleAddUserMessage` mints a `pendingTurn` whose
 * `initialMessages` is `[user_message]`; the subsequent
 * `assistant_text` / `turn_complete` events commit a `TurnEntry`
 * into `transcript`.
 *
 * Named after the substrate operation it performs — adds a
 * `user_message` Message to the substrate ([D15]). Symmetric with
 * `content_block_start { kind: "text" | "thinking" | "tool_use" }`'s
 * message-kind-keyed naming; sets the `add_<kind>` template for
 * Step 8's `add_system_note` and any future Message-creating IPC
 * event.
 *
 * No `msg_id` field. Under [D14], the reducer's `activeMsgId` is set
 * only by the first content event (`assistant_text` / `thinking_text`
 * / `tool_use` / `content_block_start`) — never pre-bound from a
 * user-side opener. The translator's `openTurnMsgId` tracker ([D13])
 * holds whatever synthesized id it minted; that id is
 * translator-internal and never reaches the wire on this frame.
 * `committedMsgIds` dedupe is therefore assistant-side-only.
 *
 * This event is only meaningful while `phase === "replaying"`; the
 * reducer drops it in any other phase so a stray frame on a live
 * session can't corrupt `pendingTurn`.
 *
 * See `roadmap/tugplan-tide-session-wake.md` [D14] (activeMsgId
 * tracking), [D15] (add_<kind> naming), and `#spec-wire-frames` for
 * the canonical wire-shape definition.
 */
export interface AddUserMessageEvent {
  type: "add_user_message";
  text: string;
  attachments?: ReadonlyArray<unknown>;
  tug_session_id?: string;
  /**
   * Stable per-turn React-key seed, generated by the store wrapper
   * before dispatch. Same contract as {@link SendActionEvent.turnKey}
   * — keeps the reducer pure.
   */
  turnKey: string;
  [key: string]: unknown;
}

/**
 * Bracket marker emitted by tugcode when claude resumes from idle in
 * response to an async deferred-completion event (Monitor timeout,
 * CronCreate firing, ScheduleWakeup arriving, etc.). The reducer
 * transitions `phase: idle → waking` and accepts the subsequent
 * assistant content that would otherwise be dropped by guards
 * expecting an active turn.
 *
 * The bracket closes implicitly on the next `turn_complete` (no
 * separate `wake_complete` event — the reducer's commit path extends
 * to map `waking → idle`).
 *
 * `wake_trigger` is a verbatim forward of the SDK's
 * `SDKTaskNotificationMessage` payload (`@anthropic-ai/claude-agent-sdk/
 * sdk.d.ts:1659-1668`). All five subfields are required — tugcode
 * forwards them as-is from the SDK event.
 *
 * Tools using active-polling (`Bash` / `Agent` with
 * `run_in_background: true`) do NOT trigger this event — they keep
 * claude actively polling rather than going idle, so there is no
 * wake to bracket.
 *
 * See `roadmap/tugplan-tide-session-wake.md` [D01], [D02] for the
 * bracket pattern and detection rationale.
 */
export interface WakeStartedEvent {
  type: "wake_started";
  session_id: string;
  wake_trigger: {
    task_id: string;
    tool_use_id: string;
    status: "completed" | "failed" | "stopped";
    summary: string;
    output_file: string;
  };
  tug_session_id?: string;
  /**
   * Stable per-turn React-key seed, generated by the store wrapper
   * (`frameToEvent`) on receipt of the wire `wake_started` frame.
   * Same minting contract as {@link AddUserMessageEvent.turnKey}
   * — the wire frame itself does not carry it; the wrapper mints
   * before dispatch to keep the reducer pure.
   */
  turnKey: string;
  [key: string]: unknown;
}

/**
 * Bracket marker emitted by the replay translator at the start of a
 * JSONL replay window. The reducer transitions
 * `phase: {idle | errored} → replaying` and gates `canSubmit` /
 * `canInterrupt` to `false` for the duration.
 */
export interface ReplayStartedEvent {
  type: "replay_started";
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * Bracket marker emitted by the replay translator at end-of-JSONL
 * (or on a hard-budget timeout). The reducer transitions
 * `phase: replaying → idle` and populates `lastReplayResult`.
 * `count` is the number of `turn_complete` events emitted during the
 * window; `error` is set for non-success terminations.
 */
export interface ReplayCompleteEvent {
  type: "replay_complete";
  count: number;
  error?: {
    kind:
      | "jsonl_missing"
      | "jsonl_unreadable"
      | "jsonl_malformed"
      | "replay_timeout";
    message: string;
  };
  tug_session_id?: string;
  [key: string]: unknown;
}

/**
 * Internal action injected by `CodeSessionStore.notifyResumeBindingLanded()`.
 * Not a wire event. The reducer flips `replayPreflightActive` to `true`
 * (only from idle + not-already-active) and emits a `schedule_timer`
 * effect for `REPLAY_PREFLIGHT_TIMEOUT_MS`. Idempotent — a second
 * `bind_resume_acknowledged` while preflight is already active is a
 * reducer no-op (no second timer is scheduled).
 */
export interface BindResumeAcknowledgedEvent {
  type: "bind_resume_acknowledged";
}

/**
 * Internal action dispatched by the soft-budget timer
 * (`REPLAY_SOFT_BUDGET_MS` after `replay_started`). The reducer flips
 * `replaySoftBudgetElapsed` to `true`. Dropped if not currently in
 * the `replaying` phase (defensive — the timer is canceled on phase
 * exit, but a race in dispatch ordering could still deliver a stale
 * tick).
 */
export interface TickSoftBudgetEvent {
  type: "tick_soft_budget";
}

/**
 * Internal action dispatched by the timeout-dwell timer
 * (`REPLAY_TIMEOUT_DWELL_MS` after `replay_complete{replay_timeout}`).
 * The reducer flips `replayTimeoutDwellActive` back to `false`,
 * dismissing the timeout banner.
 */
export interface TickTimeoutDwellDoneEvent {
  type: "tick_timeout_dwell_done";
}

/**
 * Internal action dispatched by the preflight last-resort timer
 * (`REPLAY_PREFLIGHT_TIMEOUT_MS` after `bind_resume_acknowledged`).
 * The reducer flips `replayPreflightActive` to `false`. The 12s timer
 * is the escape hatch for the case where `replay_started` never
 * lands — the banner dismisses on its own rather than hanging
 * forever.
 */
export interface TickPreflightDoneEvent {
  type: "tick_preflight_done";
}

/** Discriminated union of events the reducer accepts. */
export type CodeSessionEvent =
  | SendActionEvent
  | SessionInitEvent
  | AssistantTextEvent
  | ThinkingTextEvent
  | ContentBlockStartEvent
  | ToolUseEvent
  | ToolResultEvent
  | ToolUseStructuredEvent
  | TurnCompleteEvent
  | SystemMetadataEvent
  | ControlRequestForwardEvent
  | RespondApprovalActionEvent
  | RespondQuestionActionEvent
  | InterruptActionEvent
  | ConsumeDraftRestoreActionEvent
  | CancelQueuedSendActionEvent
  | CostUpdateEvent
  | StreamingUsageEvent
  | ContextBreakdownEvent
  | WireErrorEvent
  | SessionStateErroredEvent
  | SessionUnknownEvent
  | SessionNotOwnedEvent
  | TransportCloseEvent
  | TransportOpenEvent
  | TransportSettledEvent
  | ResumeFailedEvent
  | AddUserMessageEvent
  | ReplayStartedEvent
  | ReplayCompleteEvent
  | WakeStartedEvent
  | BindResumeAcknowledgedEvent
  | TickSoftBudgetEvent
  | TickTimeoutDwellDoneEvent
  | TickPreflightDoneEvent
  | AttachmentRejectedEvent;
